// AUTO-GENERATED -- 미국 상장 ETF의 추종(벤치마크) 지수명
const US_ETF_INDEX = {
 'SIXG':'BlueStar 5G Communications TR USD',
 'AREA':'Harbor AlphaEdge Next Gen REITs TR USD',
 'GLBL':'Bloomberg Global Aggregate TR USD',
 'ACWI':'MSCI ACWI NR USD',
 'STSB':'Change FinDivImpct US LCFsslFlFr USD',
 'BUG':'Indxx Cybersecurity v2 USD',
 'UAUG':'S&P 500 (TR) (1970)',
 'IEDI':'MSCI ACWI NR USD',
 'GCOW':'Solactive Pacer Global CashCows D TR USD',
 'PID':'Bloomberg World ex NA L & M Cap TR CAD',
 'DIVS':'S&P/TSX Preferred Share TR',
 'GXG':'MSCI All Colombia Select 25/50 NR USD',
 'TBLU':'Ecofin Global Water ESG NR USD',
 'DXJS':'WisdomTree Japan Hedged Sm Cap Eq TR USD',
 'WBAT':'WisdomTree Battery Val Chain & Inno USD',
 'PWRD':'Morningstar US Market Ext TR USD',
 'VOTE':'Morningstar US Large Select TR USD',
 'HART':'IQ Candriam healthy hearts USD',
 'DWCR':'Dorsey Wright CY&STK MTM TR USD',
 'ECLN':'S&P 500 TR USD',
 'ZZZ':'S&P 500 TR USD',
 'EBIT':'BRR USD',
 'TPHE':'Victory US LC HD L/Cash Vol Weig BRI USD',
 'TPLE':'Victory US LM L/Cash Vol Weig BRI USD',
 'NERD':'Nasdaq CTA Global Video Games Sw TR USD',
 'VEGI':'MVIS Global Future of Food ESG NR USD',
 'URNM':'North Shore Sprott Uranium Miners USD',
 'FFLC':'S&P 500 NR USD',
 'AADR':'MSCI EAFE NR USD',
 'IMOM':'Alpha Architect Inl Quant Mom NR USD',
 'QMOM':'Alpha Architect Quantitative Mom NR USD',
 'QVAL':'Alpha Architect Quantitative Val NR USD',
 'IBUY':'EQM Online Retail TR USD',
 'GYLD':'DJ Global Composite Yield TR USD',
 'CHGX':'Change Fin US LC FsslFlFr TR USD',
 'DFNL':'S&P 500 Sec/Financials TR USD',
 'DUSA':'S&P 500 Index',
 'DWLD':'MSCI ACWI Index',
 'QTUM':'BlueStar Quantum Computing and Machine Learning Index',
 'QQQE':'NASDAQ-100 Equal Weighted TR USD',
 'RFEU':'MSCI Europe NR USD',
 'GXTG':'Solactive Thematic Growth TR USD',
 'KBWR':'KBW Nasdaq Regional Banking TR USD',
 'SPVU':'S&P 500 Enhanced Value TR USD',
 'SPMV':'S&P 500 Minimum Volatility NR USD',
 'GBUG':'Barclays Gold 3 Month TR USD',
 'SZNE':'Pacer CFRA-Stovall Equal Weight Seasonal Rotation Index',
 'PTNQ':'Pacer Nasdaq-100 Trendpilot TR USD',
 'PVAL':'NASDAQ US Contrarian Value TR USD',
 'SFYX':'Solactive SoFi US Next 500 Growth TR USD',
 'SPLG':'S&P 500 TR USD',
 'HECO':'MSCI USA ESG Select Index',
 'TPYP':'Tortoise North American Pipeline TR USD',
 'CIL':'CEMP Intl 500 Vol Wgt TR USD',
 'CSA':'CEMP US Small Cap 500 Volatility Weighted TR USD',
 'USVM':'MSCI USA SC SEL Value Mmtm Bld GR USD',
 'ULVM':'MSCI USA Select Value Mmtm Bld GR USD',
 'WBIY':'Solactive Power FactorTM H Divid TR USD',
 'EUSC':'WisdomTree Europe Hdg SC Equity TR USD',
 'SHLD':'Nasdaq Yewno Aerospace & Defen TR USD',
 'JOET':'Terranova US Quality Momen TR USD',
 'JEMA':'MSCI EM NR USD',
 'XCLR':'MSCI Cda IMI Et ESG Ld 10% Is Cp NR CAD',
 'MBCC':'Kingsview Blue Chips Core TR USD',
 'FTLS':'S&P 500 (TR) (1970)',
 'GBLD':'MSCI Global Green Building USD',
 'HYDR':'Solactive Global Hydrogen TR CAD',
 'JETS':'US Global Jets NR USD',
 'BLKC':'Alerian Galaxy Global Blockchain Equity, Trusts & ETP USD',
 'FDHT':'Fidelity Digital Health TR USD',
 'CLNR':'IQ Candriam Cleaner Transport USD',
 'QQJG':'Nasdaq Next Generation 100 ESG USD',
 'GMET':'MVIS Global Clean-Tech Metals USD',
 'TAGS':'LBMA Silver Price USD',
 'ESIX':'S&P SmallCap 600 ESG TR USD',
 'DMAT':'Solactive Disruptive Materials TR USD',
 'LRND':'IQ US Large Cap R&D Leaders USD',
 'WRND':'IQ Global Equity R&D Leaders USD',
 'METV':'Ball Metaverse TR USD',
 'PAWZ':'Foxberry Pet Care NR USD',
 'IUSG':'Bloomberg Euro Corp TR EUR',
 'NZUS':'USA Climate Paris Aligned NR USD',
 'EMXC':'MSCI EM ex China NR USD',
 'INDA':'STOXX Europe 600 Banks NR EUR',
 'CGV':'MSCI ACWI Value NR USD',
 'DRLL':'Solactive US Energy Regulated Cap TR USD',
 'KPOP':'KPOP TR USD',
 'FCLD':'Fidelity Cloud Comput ESG Tilted NR USD',
 'FDRV':'Fidelity EV Fut Trans ESG Tilt NR USD',
 'STRV':'Solactive GBS United States 500 TR USD',
 'SHOC':'Solactive US Semicond 30 Cap TR USD',
 'MCSE':'MSCI ACWI Ex USA NR USD',
 'STXG':'Bloomberg US 1000 Growth TR USD',
 'STXK':'Bloomberg US 2000 TR USD',
 'STXE':'Bloomberg EM ex China L&M TR USD',
 'FRNW':'Fidelity Clean Energy ESG Tilted NR USD',
 'FMQQ':'FMQQ Nxt Frnt Int & Ecom ESG Scrn NR USD',
 'KARS':'Bloomberg EV ESG Screened TR USD',
 'CLOU':'JPM Euro Collater Loan Oblig AAA TR EUR',
 'SKYY':'Solactive Cloud Technology EW NR USD',
 'FDWM':'Russell 3000 TR USD',
 'FSST':'Russell 3000 TR USD',
 'ESG':'iEdge-OCBC SG Low Carb Slct 50 Cap SGD',
 'CFA':'FTSE EPRA Nareit Asia ex JAP REIT NR SGD',
 'TDIV':'Morningstar DM Lrg Div Leader Sel GR EUR',
 'BTAL':'S&P 500 (TR) (1970)',
 'ENFR':'Bloomberg US 1000 TR USD',
 'AMLP':'Bloomberg US 1000 TR USD',
 'ACES':'Bloomberg US 1000 TR USD',
 'DTEC':'Morningstar Global Markets NR USD',
 'EQL':'S&P 500 (TR)',
 'IDOG':'Morningstar DM xNA NR USD',
 'SBIO':'Bloomberg US 1000 TR USD',
 'RDOG':'Bloomberg US 1000 TR USD',
 'SDOG':'S&P 500 (TR) (1970)',
 'ARKF':'S&P 500 (TR) (1970)',
 'ARKG':'S&P 500 (TR) (1970)',
 'ARKK':'S&P 500 (TR) (1970)',
 'IZRL':'S&P 500 (TR) (1970)',
 'ARKW':'S&P 500 (TR) (1970)',
 'BFOR':'Bloomberg US 1000 Val TR USD',
 'OUSA':'Bloomberg US 1000 Val TR USD',
 'OGIG':'Bloomberg US 1000 TR USD',
 'RFDA':'S&P 500 (TR) (1970)',
 'RFFC':'Bloomberg US 1000 TR USD',
 'REIT':'Bloomberg US 1000 TR USD',
 'ARKQ':'S&P 500 (TR) (1970)',
 'OUSM':'Bloomberg US 1000 Val TR USD',
 'PRNT':'S&P 500 (TR) (1970)',
 'ARKX':'S&P 500 (TR) (1970)',
 'HIDV':'S&P 500 (TR) (1970)',
 'DRN':'VettaFi Drone TR USD',
 'LOWV':'S&P 500 (TR) (1970)',
 'LGRO':'Bloomberg US 1000 TR USD',
 'LRGC':'S&P 500 (TR) (1970)',
 'NIXT':'Research Affiliates Deletions TR USD',
 'FLDZ':'S&P 900 TR',
 'LSVD':'S&P 500 (TR) (1970)',
 'ROPE':'Solactive GBS United States 1000 TR USD',
 'INVN':'Alger Russell Innovation TR USD',
 'AFSC':'Russell 3000 TR USD',
 'AGEM':'MSCI EM NR USD',
 'DWSH':'S&P 500 (TR) (1970)',
 'CAMX':'Russell 3000 TR USD',
 'CWS':'S&P 500 (TR) (1970)',
 'VEGA':'MSCI ACWI NR USD',
 'FRDM':'Solactive GBS EM L&M Cap TR USD',
 'WBIF':'S&P 500 (TR) (1970)',
 'WBIG':'S&P 500 (TR) (1970)',
 'DEMZ':'S&P 500 (TR) (1970)',
 'FRTY':'S&P 500 (TR) (1970)',
 'ATFV':'S&P 500 (TR) (1970)',
 'GK':'S&P 500 (TR) (1970)',
 'PSIL':'S&P 500 (TR) (1970)',
 'GFGF':'Solactive GBS United States 1000 NR USD',
 'AOTG':'Solactive GBS United States 1000 NR USD',
 'LCLG':'Russell 1000 TR USD',
 'SURE':'Russell 3000 TR USD',
 'BBLU':'S&P 500 (TR) (1970)',
 'BRNY':'S&P Composite 1500 TR USD',
 'SHDG':'S&P 500 (TR) (1970)',
 'WBIL':'S&P 500 (TR) (1970)',
 'DWUS':'S&P 500 (TR) (1970)',
 'SAMT':'S&P 500 NR USD',
 'ABCS':'Bloomberg US Agg Eqty TR USD',
 'CNEQ':'S&P 500 (TR) (1970)',
 'BSVO':'Russell 3000 TR USD',
 'BDGS':'S&P 500 (TR)',
 'SMRI':'Solactive GBS United States 1000 TR USD',
 'BEEZ':'Solactive GBS United States 500 TR USD',
 'CARK':'Russell 1000 TR USD',
 'LBO':'S&P 500 (TR)',
 'FTWO':'Bloomberg US 1000 TR USD',
 'STXD':'Bloomberg US 1000 TR USD',
 'MVPA':'S&P 500 (TR) (1970)',
 'KEAT':'Solactive GBS United States 1000 TR USD',
 'RVER':'S&P 500 (TR) (1970)',
 'SAMM':'S&P 500 (TR) (1970)',
 'ALAI':'S&P 500 (TR) (1970)',
 'THNR':'S&P 500 (TR) (1970)',
 'AIVC':'S&P 500 (TR) (1970)',
 'BKDV':'Russell 1000 TR USD',
 'ACLC':'S&P 500 (TR) (1970)',
 'EMPB':'Solactive GBS Glb Mar All Cap USD TR',
 'TAX':'Solactive GBS United States 1000 TR USD',
 'TOV':'JLens 500 Jewish Advocacy US TR USD',
 'VALQ':'Russell 1000 TR USD',
 'QGRO':'Russell 1000 TR USD',
 'BATT':'S&P 500 (TR)',
 'AVDE':'MSCI World Ex USA IMI NR USD',
 'AVUS':'Russell 3000 TR USD',
 'AVUV':'Russell 3000 TR USD',
 'AVEM':'MSCI EM IMI NR USD',
 'GDMA':'Solactive us agg bond TR USD',
 'FLV':'Russell 1000 TR USD',
 'ARB':'S&P 500 (TR) (1970)',
 'MBOX':'Solactive GBS US 1000 TR USD',
 'AVLV':'Russell 1000 TR USD',
 'EVNT':'S&P 500 (TR) (1970)',
 'AVES':'MSCI EM IMI NR USD',
 'AVIV':'MSCI World ex USA NR USD',
 'AVRE':'MSCI World IMI NR USD',
 'AVSC':'Russell 3000 TR USD',
 'AVSD':'MSCI World Ex USA IMI NR USD',
 'AVSU':'Russell 3000 TR USD',
 'AVSE':'MSCI EM IMI NR USD',
 'AMID':'Russell 3000 TR USD',
 'NDIV':'MSCI ACWI Ex USA NR USD',
 'IDVO':'MSCI ACWI Ex USA NR USD',
 'AVIE':'Russell 3000 TR USD',
 'MID':'Russell 3000 TR USD',
 'ACGR':'Russell 1000 TR USD',
 'MAVF':'S&P 500 (TR) (1970)',
 'FDG':'Russell 1000 TR USD',
 'COWS':'S&P 500 (TR) (1970)',
 'AVLC':'Russell 1000 TR USD',
 'AVEE':'MSCI Emerging Markets Small Cap NR USD',
 'AVMC':'Russell 3000 TR USD',
 'AVMV':'Russell 3000 TR USD',
 'MGNR':'S&P 500 (TR)',
 'BGRO':'Russell 1000 Growth TR USD',
 'CSHP':'Bloomberg Global Aggregate TR USD',
 'THRO':'S&P 500 (TR) (1970)',
 'BAI':'S&P 500 (TR) (1970)',
 'OWNB':'Bitwise Bitcoin Standard Corp PR USD',
 'BITQ':'S&P 500 (TR) (1970)',
 'DYNF':'MSCI USA NR USD',
 'BKLC':'S&P 500 (TR) (1970)',
 'BKMC':'S&P Composite 1500 TR USD',
 'BKSE':'S&P Composite 1500 TR USD',
 'BKEM':'MSCI EM NR USD',
 'LCTU':'Russell 1000 TR USD',
 'BKCI':'MSCI EAFE NR USD',
 'BLCV':'Russell 1000 TR USD',
 'FFSM':'Russell 2500 NR USD',
 'BALI':'S&P 500 (TR) (1970)',
 'BLCR':'Russell 1000 TR USD',
 'INRO':'MSCI USA NR USD',
 'EQIN':'Russell 3000 TR USD',
 'INEQ':'MSCI EAFE NR USD',
 'NITE':'S&P 500 (TR)',
 'IDVZ':'S&P 500 (TR) (1970)',
 'EYLD':'MSCI EM NR USD',
 'GAA':'Bloomberg Global Aggregate TR USD',
 'SYLD':'S&P 500 (TR) (1970)',
 'VAMO':'S&P 500 (TR) (1970)',
 'XCEM':'MSCI EM NR USD',
 'ECON':'MSCI EM NR USD',
 'RECS':'Russell 1000 TR USD',
 'LRNZ':'NASDAQ Composite TR USD',
 'CBSE':'Bloomberg World All Cap Eq Weight TR USD',
 'RULE':'S&P 500 (TR) (1970)',
 'GHTA':'Bloomberg Wld LnM CapTR USD',
 'TACK':'Russell 1000 Equal Weight TR USD',
 'SRHQ':'S&P 500 (TR) (1970)',
 'SOVF':'S&P Composite 1500 Equal Weight TR USD',
 'BOUT':'S&P 500 (TR) (1970)',
 'FFTY':'S&P 500 (TR) (1970)',
 'GVAL':'MSCI ACWI NR USD',
 'REVS':'Russell 1000 TR USD',
 'MFUL':'Bloomberg US Agg Bond TR USD',
 'CGBL':'S&P 500 (TR) (1970)',
 'SRHR':'S&P 500 (TR) (1970)',
 'XAIX':'Nasdaq Global AI and Big Data TR USD',
 'DXIV':'MSCI World Ex USA IMI NR USD',
 'DXUV':'Russell 3000 TR USD',
 'EMCS':'MSCI EM NR USD',
 'DEXC':'MSCI EM ex China NR USD',
 'DFEN':'S&P 500 (TR) (1970)',
 'WANT':'S&P 500 (TR) (1970)',
 'WEBL':'S&P 500 (TR) (1970)',
 'FAS':'S&P 500 (TR) (1970)',
 'EURL':'S&P 500 (TR) (1970)',
 'CURE':'S&P 500 (TR) (1970)',
 'DUSL':'S&P 500 (TR) (1970)',
 'PILL':'S&P 500 (TR) (1970)',
 'DPST':'S&P 500 (TR) (1970)',
 'SPUU':'S&P 500 (TR) (1970)',
 'LABU':'S&P 500 (TR) (1970)',
 'GUSH':'S&P 500 (TR) (1970)',
 'SPXL':'S&P 500 (TR) (1970)',
 'TNA':'S&P 500 (TR) (1970)',
 'TECL':'S&P 500 (TR) (1970)',
 'TPOR':'S&P 500 (TR) (1970)',
 'UTSL':'S&P 500 (TR) (1970)',
 'DEEF':'FTSE Developed ex-U.S. NR USD',
 'HDEF':'MSCI EAFE NR USD',
 'DBEZ':'MSCI EMU IMI NR USD',
 'DBJP':'MSCI Japan NR USD',
 'USSG':'MSCI USA NR USD',
 'DEUS':'Russell 1000 TR USD',
 'SNPE':'S&P 500 (TR) (1970)',
 'KOKU':'MSCI World NR USD',
 'DFAI':'MSCI World Ex USA IMI NR USD',
 'DFAU':'Russell 3000 TR USD',
 'DFAE':'MSCI EM IMI NR USD',
 'MIDE':'S&P Composite 1500 (TR) USD',
 'DFAC':'Russell 3000 TR USD',
 'DFAS':'Russell 3000 TR USD',
 'DFAT':'Russell 3000 TR USD',
 'DFUS':'Russell 3000 TR USD',
 'EMCR':'MSCI EM NR USD',
 'DFAX':'MSCI ACWI Ex USA IMI NR USD',
 'DFIV':'MSCI World ex USA NR USD',
 'FNGG':'S&P 500 (TR) (1970)',
 'GUNZ':'AJN Self Defense US Equity TR USD',
 'DFAR':'Russell 3000 TR USD',
 'DFSV':'Russell 3000 TR USD',
 'DUHP':'Russell 1000 TR USD',
 'DFIC':'MSCI World Ex USA IMI NR USD',
 'DIHP':'MSCI World ex USA NR USD',
 'FIVY':'Nasdaq Dorsey Wright T H O I S TR USD',
 'DEHP':'MSCI EM NR USD',
 'DFEV':'MSCI EM NR USD',
 'USNZ':'S&P 500 (TR) (1970)',
 'DFSE':'MSCI EM IMI NR USD',
 'DFSI':'MSCI World Ex USA IMI NR USD',
 'DFSU':'Russell 3000 TR USD',
 'SNPD':'S&P Composite 1500 (TR) USD',
 'SNPG':'S&P 500 (TR) (1970)',
 'DFGR':'MSCI All Country World IMI',
 'DFLV':'Russell 1000 TR USD',
 'DBEM':'MSCI EM NR USD',
 'QARP':'Russell 1000 TR USD',
 'DFEM':'MSCI EM IMI NR USD',
 'USCA':'MSCI USA NR USD',
 'UPGR':'S&P Composite 1500 TR USD',
 'DCOR':'Russell 3000 TR USD',
 'DFVX':'Russell 1000 TR USD',
 'FILL':'MSCI ACWI Select Energy Prod IMI NR USD',
 'CRTC':'Solactive Whitney U.S. Crit Tech NR USD',
 'URAA':'S&P 500 (TR) (1970)',
 'BDIV':'S&P 500 (TR) (1970)',
 'SAWG':'S&P 500 (TR) (1970)',
 'SAWS':'S&P 500 (TR) (1970)',
 'XRLV':'S&P 500 Low Volatility Rate Rep TR USD',
 'CEPI':'S&P 500 (TR) (1970)',
 'BGDV':'S&P 500 (TR) (1970)',
 'WAR':'S&P 500 (TR) (1970)',
 'SPDV':'S&P 500 (TR) (1970)',
 'ACIO':'S&P 500 (TR) (1970)',
 'ADME':'S&P 500 (TR) (1970)',
 'OCIO':'ICE BofA US Broad Market TR USD',
 'DFND':'Siren DIVCON Dividend Defender TR USD',
 'BJK':'MVIS Global Gaming NR USD',
 'ERX':'S&P 500 (TR) (1970)',
 'NAIL':'S&P 500 (TR) (1970)',
 'RETL':'S&P 500 (TR) (1970)',
 'HIBL':'S&P 500 (TR) (1970)',
 'NETL':'S&P 500 (TR) (1970)',
 'OSCV':'S&P 500 (TR) (1970)',
 'PPTY':'S&P 500 (TR) (1970)',
 'ZIG':'S&P 500 (TR) (1970)',
 'DSTX':'Distillate Int Fund Stb & Val TR USD',
 'OCEN':'IQ Candriam Clean Oceans USD',
 'IPDP':'NASDAQ US Broad Div Achievers TR USD',
 'GLOV':'Goldman Sachs ActBt Wld LwVol + Eq USD',
 'VUSE':'S&P 500 (TR) (1970)',
 'VIDI':'Morningstar Global Markets xUS NR USD',
 'BBC':'FT Wilshire 5000 TR USD',
 'VRAI':'FT Wilshire 5000 TR USD',
 'UTES':'S&P 500 (TR) (1970)',
 'FORH':'S&P 500 (TR)',
 'VSLU':'Morningstar US Market TR USD',
 'RIET':'S&P 500 (TR) (1970)',
 'MSMR':'S&P 500 (TR) (1970)',
 'RITA':'S&P 500 (TR) (1970)',
 'SEA':'S&P 500 (TR) (1970)',
 'REMX':'MVIS Glb RareEarth/Strategic Mtls TR USD',
 'JSMD':'MSCI EM SRI EU PAB Overlay ESG C NR USD',
 'RFCI':'Bloomberg US Agg Bond TR USD',
 'LGCF':'Solactive Commodity Composite PR USD',
 'FWD':'MSCI ACWI NR USD',
 'EDGF':'Bloomberg US Agg Bond TR USD',
 'KNG':'CBOE S&P 500 Div Aristocrats Tgt Inc USD',
 'VICE':'MSCI ACWI NR USD',
 'QPX':'S&P 500 (TR) (1970)',
 'SAGP':'MSCI ACWI NR USD',
 'MEDX':'VettaFi Eq Weight Gbl Healthcare TR CAD',
 'TBG':'S&P 500 (TR) (1970)',
 'EQLT':'S&P/TSX 60 Equal Weight TR CAD',
 'BLOK':'MSCI ACWI NR USD',
 'DTRE':'Alerian Disruptive Tech Real Estate USD',
 'DIVO':'S&P 500 (TR) (1970)',
 'HCOW':'S&P 500 (TR) (1970)',
 'BELT':'S&P 500 TR USD',
 'ROE':'S&P 500 (TR)',
 'TEK':'MSCI ACWI NR USD',
 'BIDD':'MSCI ACWI Ex USA NR USD',
 'CORO':'MSCI ACWI Ex USA NR USD',
 'BKCH':'Solactive Blockchain v2 USD',
 'PATN':'Nasdaq Int Patent Leaders TR USD',
 'QSIX':'S&P 500 (TR) (1970)',
 'KROP':'Solactive AgTech & Food Inno v2 USD',
 'FOWF':'MSCI World NR USD',
 'PEVC':'FTSE PE/VC TR USD',
 'BMED':'MSCI ACWI NR USD',
 'BPAY':'MSCI ACWI NR USD',
 'BKGI':'MSCI ACWI NR USD',
 'QQQG':'Pacer Nasdaq100 Top 50 CC Growth TR USD',
 'NXTG':'MSCI ACWI NR CAD',
 'PABU':'S&P 500 NZ 2050 Paris-Aligned ESG NR USD',
 'USMC':'Solactive US Mega Cap 100 Select NR USD',
 'IVVB':'S&P 500 (TR) (1970)',
 'IVVM':'S&P 500 (TR) (1970)',
 'BULD':'S&P Global 1200 TR',
 'SHPP':'Pacer Global Supply Chain Infra TR USD',
 'TRFK':'S&P 1200 TR USD',
 'CAFG':'S&P Composite 1500 TR USD',
 'TOUS':'MSCI EAFE NR USD',
 'CATH':'MSCI Wld Sel Ca Pri ESG Univ&Env NR USD',
 'USMV':'US ESG Minimum Variance NR USD',
 'BLDG':'MSCI ACWI NR USD',
 'HELO':'S&P 500 (TR) (1970)',
 'SEMI':'MSCI ACWI NR USD',
 'MAGS':'Solactive Magnificent 7 TR USD',
 'PBD':'FTSE TMX Canada Universe Bond TR CAD',
 'TYD':'Bloomberg US Agg Bond TR USD',
 'SOXL':'S&P 500 (TR) (1970)',
 'DBAW':'MSCI ACWI Ex USA NR USD',
 'MLPX':'Solactive US Energy Infra MLP TR USD',
 'CHPS':'MSCI ACWI NR USD',
 'PSWD':'MSCI ACWI NR USD',
 'HLAL':'FTSE USA Shariah TR USD',
 'SMOT':'Morningstar US SMID Moat Focus TR USD',
 'INQQ':'INQQ The India Internet ESG Scrd USD',
 'SETM':'Nasdaq Sprott Energy Transition Mat USD',
 'AQWA':'Solactive Global Clean Water Ind v2 USD',
 'QGRW':'WisdomTree US Qual Grwth UCITS NR USD',
 'NATO':'EQM Future of Defence NR USD',
 'TSPY':'S&P 500 (TR) (1970)',
 'JGRO':'Russell 1000 Growth NR USD',
 'HF':'S&P 500 TR USD',
 'FPAG':'MSCI ACWI NR USD',
 'FDIG':'MSCI ACWI NR USD',
 'FMET':'MSCI ACWI NR USD',
 'JAVA':'Russell 1000 Value NR USD',
 'FBOT':'MSCI ACWI NR USD',
 'NUKZ':'MSCI ACWI NR USD',
 'FDCF':'MSCI ACWI NR USD',
 'FDFF':'MSCI ACWI NR USD',
 'FDTX':'MSCI ACWI NR USD',
 'FMED':'MSCI ACWI NR USD',
 'DYFI':'Bloomberg US Agg Bond TR USD',
 'COAL':'MSCI ACWI NR USD',
 'WCMI':'MSCI ACWI Ex USA NR USD',
 'FFGX':'MSCI ACWI Ex USA NR USD',
 'DDIV':'S&P 500 (TR) (1970)',
 'FDNI':'MSCI ACWI Ex USA NR USD',
 'QUVU':'Russell 1000 Value TR USD',
 'FTAG':'MSCI ACWI NR USD',
 'KGRN':'MSCI CHINA IMI ENVIRONMENT 10-40 NR USD',
 'FPXI':'MSCI ACWI Ex USA NR USD',
 'CARZ':'MSCI ACWI NR USD',
 'ISHP':'MSCI ACWI NR USD',
 'ARVR':'MSCI ACWI NR USD',
 'FTQI':'S&P 500 (TR) (1970)',
 'RDVY':'S&P 500 (TR) (1970)',
 'NTSX':'WisdomTree US Eff Core UCITS TR USD',
 'IRET':'iREIT-MarketVector Quality REIT NR USD',
 'AGQI':'MSCI ACWI NR USD',
 'COPA':'Bloomberg commSub Copper TR USD',
 'STXM':'Bloomberg US 400 TR USD',
 'NXTV':'Next Intangible Value TR USD',
 'RSSL':'S&P 500 (TR) (1970)',
 'IPAV':'MSCI ACWI NR USD',
 'SLVR':'Bloomberg Comm Silver Subindex TR GBP',
 'GNOM':'MSCI ACWI NR USD',
 'CTEC':'MSCI ACWI NR USD',
 'RNRG':'MSCI ACWI NR USD',
 'WTRE':'WisdomTree New Economy RealEstate TR USD',
 'DRIV':'MSCI ACWI NR USD',
 'COPX':'MSCI ACWI NR USD',
 'EBIZ':'MSCI ACWI NR USD',
 'FINX':'MSCI ACWI NR USD',
 'AIQ':'MSCI ACWI NR USD',
 'GOEX':'MSCI ACWI NR USD',
 'SNSR':'MSCI ACWI NR USD',
 'LIT':'MSCI ACWI NR USD',
 'QYLD':'S&P 500 (TR) (1970)',
 'BOTZ':'MSCI ACWI NR USD',
 'RYLD':'S&P 500 (TR) (1970)',
 'SIL':'MSCI ACWI NR USD',
 'SOCL':'MSCI ACWI NR USD',
 'URA':'MSCI ACWI NR USD',
 'HERO':'MSCI ACWI NR USD',
 'XYLG':'S&P 500 (TR) (1970)',
 'QYLG':'S&P 500 (TR) (1970)',
 'AGNG':'MSCI ACWI NR USD',
 'XRMI':'S&P 500 (TR) (1970)',
 'QRMI':'S&P 500 (TR) (1970)',
 'XYLD':'S&P 500 (TR) (1970)',
 'ESGE':'MSCI EAFE ESG-Leaders TR CAD',
 'DYLG':'S&P 500 (TR) (1970)',
 'XFLX':'Bloomberg US Agg Bond TR USD',
 'DTCR':'MSCI ACWI NR USD',
 'SRET':'MSCI ACWI NR USD',
 'GINN':'MSCI ACWI NR USD',
 'GTEK':'MSCI ACWI NR USD',
 'GDOC':'MSCI ACWI NR USD',
 'DJIA':'S&P 500 (TR) (1970)',
 'SDIV':'MSCI ACWI NR USD',
 'ONEQ':'MSCI World NR CAD',
 'UMI':'WisdomTree U.S. MidCap Div CAD',
 'GPIQ':'S&P 500 (TR) (1970)',
 'UJUL':'S&P 500 (TR) (1970)',
 'JAJL':'S&P 500 (TR) (1970)',
 'EALT':'S&P 500 (TR) (1970)',
 'RSPA':'S&P 500 (TR) (1970)',
 'RING':'Mirae Asset EW Can Telecom GR CAD',
 'PSP':'MSCI ACWI NR USD',
 'ERTH':'MSCI ACWI NR USD',
 'DRUP':'Solactive Global Memory Chips TR USD',
 'IPKW':'MSCI ACWI Ex USA NR USD',
 'CUT':'MSCI ACWI NR USD',
 'SPHD':'S&P 500 (TR) (1970)',
 'SPLV':'S&P 500 (TR) (1970)',
 'TAN':'MSCI ACWI NR USD',
 'SATO':'MSCI ACWI NR USD',
 'KLMT':'MSCI ACWI NR USD',
 'ACWV':'MSCI ACWI NR USD',
 'EWK':'MSCI ACWI Ex USA NR USD',
 'EFG':'MSCI ACWI Ex USA NR USD',
 'EFV':'MSCI ACWI Ex USA NR USD',
 'EZU':'MSCI ACWI Ex USA NR USD',
 'EWQ':'MSCI ACWI Ex USA NR USD',
 'EWG':'MSCI ACWI Ex USA NR USD',
 'SLVP':'MSCI ACWI NR USD',
 'EWH':'MSCI ACWI Ex USA NR USD',
 'EIS':'MSCI ACWI Ex USA NR USD',
 'TOK':'MSCI ACWI NR USD',
 'EWN':'MSCI ACWI Ex USA NR USD',
 'ACWX':'MSCI ACWI Ex USA NR USD',
 'URTH':'MSCI ACWI NR USD',
 'ARTY':'MSCI ACWI NR USD',
 'IXUS':'MSCI ACWI Ex USA NR USD',
 'HEFA':'MSCI ACWI Ex USA NR USD',
 'IHAK':'MSCI ACWI NR USD',
 'IVLU':'MSCI ACWI Ex USA NR USD',
 'XT':'MSCI ACWI NR USD',
 'IGRO':'MSCI ACWI Ex USA NR USD',
 'CRBN':'MSCI ACWI NR USD',
 'EFNL':'MSCI ACWI Ex USA NR USD',
 'SDG':'MSCI ACWI NR USD',
 'PICK':'MSCI ACWI NR USD',
 'EWI':'MSCI ACWI Ex USA NR USD',
 'EWJ':'MSCI ACWI Ex USA NR USD',
 'EWJV':'MSCI ACWI Ex USA NR USD',
 'EWS':'MSCI ACWI Ex USA NR USD',
 'EWU':'MSCI ACWI Ex USA NR USD',
 'IDRV':'MSCI ACWI NR USD',
 'DMXF':'MSCI ACWI Ex USA NR USD',
 'IBLC':'MSCI ACWI NR USD',
 'IBRN':'MSCI ACWI NR USD',
 'IVRS':'MSCI ACWI NR USD',
 'IDNA':'MSCI ACWI NR USD',
 'ETEC':'MSCI ACWI NR USD',
 'JIG':'MSCI ACWI Ex USA NR USD',
 'JIVE':'MSCI ACWI Ex USA NR USD',
 'LVHI':'MSCI ACWI Ex USA NR USD',
 'TUGN':'Morningstar Mod Tgt Risk TR USD',
 'CVRD':'S&P 500 (TR) (1970)',
 'VGSR':'MSCI ACWI NR USD',
 'PCCE':'MSCI ACWI Ex USA NR USD',
 'ESN':'S&P 500 (TR) (1970)',
 'BIBL':'S&P 500 (TR) (1970)',
 'GSIB':'Bloomberg Global Aggregate TR Hdg USD',
 'MAMB':'Bloomberg US Agg Bond TR USD',
 'FMCX':'S&P 500 (TR) (1970)',
 'PJFV':'S&P 500 (TR) (1970)',
 'BAMB':'Bloomberg US Agg Bond TR USD',
 'PJIO':'MSCI ACWI Ex USA NR USD',
 'IQRA':'MSCI World NR USD',
 'PIEQ':'MSCI ACWI Ex USA NR USD',
 'VERS':'MSCI ACWI NR USD',
 'MAPP':'S&P 500 (TR) (1970)',
 'DIG':'S&P 500 (TR) (1970)',
 'TMFC':'S&P 500 (TR) (1970)',
 'VLLU':'S&P 500 (TR) (1970)',
 'PEMX':'MSCI ACWI Ex USA NR USD',
 'FEZ':'MSCI ACWI Ex USA NR USD',
 'QEMM':'MSCI ACWI Ex USA NR USD',
 'SPDW':'MSCI ACWI Ex USA NR USD',
 'SPY':'S&P 500 (TR) (1970)',
 'GXC':'MSCI ACWI Ex USA NR USD',
 'EWX':'MSCI ACWI Ex USA NR USD',
 'GWX':'MSCI ACWI Ex USA NR USD',
 'DECO':'MSCI ACWI NR USD',
 'SCHM':'S&P 500 (TR) (1970)',
 'SCHA':'S&P 500 (TR) (1970)',
 'EEMX':'MSCI ACWI Ex USA NR USD',
 'SPYD':'S&P 500 (TR) (1970)',
 'XCNY':'MSCI ACWI Ex USA NR USD',
 'CRDT':'Bloomberg US Agg Bond TR USD',
 'SSXU':'MSCI ACWI Ex USA NR USD',
 'SPAM':'MSCI ACWI NR USD',
 'CLOD':'MSCI ACWI NR USD',
 'SFYF':'S&P 500 (TR) (1970)',
 'SFY':'S&P 500 (TR) (1970)',
 'ABLG':'MSCI ACWI Ex USA NR USD',
 'SIO':'Bloomberg US Agg Bond TR USD',
 'SMHX':'MSCI ACWI NR USD',
 'MOO':'MSCI ACWI NR USD',
 'BBH':'MSCI ACWI NR USD',
 'EINC':'MSCI ACWI NR USD',
 'EVX':'MSCI ACWI NR USD',
 'GDX':'MSCI ACWI NR USD',
 'GDXJ':'MSCI ACWI NR USD',
 'HAP':'MSCI ACWI NR USD',
 'CRAK':'MSCI ACWI NR USD',
 'OIH':'MSCI ACWI NR USD',
 'PPH':'MSCI ACWI NR USD',
 'RTH':'MSCI ACWI NR USD',
 'SMH':'MSCI ACWI NR USD',
 'SLX':'MSCI ACWI NR USD',
 'NLR':'MSCI ACWI NR USD',
 'ESPO':'MSCI ACWI NR USD',
 'BUZZ':'S&P 500 (TR) (1970)',
 'DAPP':'MSCI ACWI NR USD',
 'MOTG':'MSCI ACWI NR USD',
 'OAIM':'MSCI ACWI Ex USA NR USD',
 'SMOG':'MSCI ACWI NR USD',
 'VCEB':'Bloomberg US Agg Bond TR USD',
 'IBOT':'MSCI ACWI NR USD',
 'DESK':'MSCI ACWI NR USD',
 'VOO':'S&P 500 (TR) (1970)',
 'DNL':'MSCI ACWI Ex USA NR USD',
 'SEEM':'MSCI EM NR USD',
 'SEIE':'MSCI EAFE NR USD',
 'VOLT':'S&P 500 (TR)',
 'HYIN':'Bloomberg US Agg Bond TR USD',
 'GRNY':'S&P 500 (TR)',
 'GMOI':'MSCI World ex USA NR USD',
 'GMOV':'MSCI USA GR USD',
 'QLTI':'MSCI World ex USA NR USD',
 'QLTY':'S&P 500 (TR)',
 'WTBN':'Bloomberg US Agg Bond TR USD',
 'APIE':'S&P Global BMI TR USD',
 'APUE':'Morningstar US Total Market TR USD',
 'WLTG':'S&P 500 (TR) (1970)',
 'DIVZ':'S&P 500 (TR) (1970)',
 'CGGO':'MSCI ACWI NR USD',
 'CGXU':'MSCI ACWI Ex USA NR USD',
 'RNWZ':'MSCI World NR USD',
 'WOMN':'S&P/TSX Composite TR USD',
 'CGDG':'MSCI ACWI NR USD',
 'DINT':'MSCI ACWI Ex USA NR USD',
 'DIVY':'S&P 500 TR CAD',
 'KRMA':'S&P 500 (TR) (1970)',
 'METU':'Solactive Global Metaverse Innov NR USD',
 'ACVF':'S&P 500 (TR) (1970)',
 'HOMZ':'S&P 500 (TR) (1970)',
 'SEIM':'S&P 500 (TR)',
 'SEIV':'S&P 500 (TR)',
 'SELV':'S&P 500 (TR)',
 'SEIQ':'S&P 500 (TR)',
 'BGIG':'S&P 500 (TR) (1970)',
 'FKU':'NASDAQ AlphaDEX(R) United Kingdom NR GBP',
 'QLVE':'MSCI EM NR USD',
 'TILT':'Russell 3000 TR USD',
 'INDE':'MSCI Ind Uni Low Cb Sel 5% Is Cap NR USD',
 'QLVD':'MSCI World ex USA NR USD',
 'GQRE':'MSCI World NR USD',
 'IQDY':'MSCI ACWI Ex USA NR USD',
 'IQDF':'MSCI ACWI Ex USA NR USD',
 'TLTE':'MSCI EM NR USD',
 'QDEF':'Russell 1000 TR USD',
 'GUNR':'MSCI ACWI NR USD',
 'FEUS':'Russell 1000 TR USD',
 'QLC':'S&P 500 (TR)',
 'QDF':'Russell 1000 TR USD',
 'ESGG':'MSCI World NR USD',
 'QLV':'Russell 1000 TR USD',
 'CGIC':'MSCI ACWI Ex USA NR USD',
 'SPYX':'MSCI EM Small NR USD',
 'QCLN':'NASDAQ Clean Edge Green Energy TR USD',
 'IUSV':'ICE U.S. Treasury 20+ Year Bond TR USD',
 'EMQQ':'EMQQ The EM Internet ESG- Scre USD',
 'OSEA':'MSCI ACWI Ex USA NR USD',
 'WDNA':'WisdomTree BioRevolution ESG Scrn NR USD',
 'CAPE':'S&P 500 (TR) (1970)',
 'TRFM':'S&P 500 (TR) (1970)',
 'HCMT':'S&P 500 (TR) (1970)',
 'SCDV':'S&P 500 (TR) (1970)',
 'DSTL':'S&P 500 (TR) (1970)',
 'VEGN':'S&P 500 (TR) (1970)',
 'BBP':'FT Wilshire 5000 TR USD',
 'DEEP':'S&P 500 (TR) (1970)',
 'SMIG':'S&P 500 (TR) (1970)',
 'DSMC':'Morningstar Global Markets xUS GR USD',
 'DFVE':'S&P 500 Equal Weighted TR USD',
 'QQQU':'S&P 500 (TR) (1970)',
 'AIBU':'S&P 500 (TR) (1970)',
 'FCTE':'S&P 500 (TR) (1970)',
 'FLCC':'Russell 3000 TR USD',
 'FLCG':'Russell 3000 TR USD',
 'FLCV':'Russell 3000 TR USD',
 'FSCC':'Russell 3000 TR USD',
 'XOVR':'Russell 1000 Growth TR USD',
 'KDEF':'Korea Defense Industry USD',
 'AIFD':'S&P 500 (TR) (1970)',
 'GRW':'S&P 500 (TR) (1970)',
 'FDIS':'S&P 500 (TR) (1970)',
 'FSTA':'S&P 500 (TR) (1970)',
 'FENY':'S&P 500 (TR) (1970)',
 'FNCL':'S&P 500 (TR) (1970)',
 'FCPI':'Russell 1000 TR USD',
 'HTEC':'S&P 500 (TR) (1970)',
 'ROBO':'S&P 500 (TR) (1970)',
 'SSPY':'S&P 500 (TR) (1970)',
 'SIXA':'S&P 500 (TR) (1970)',
 'SIXL':'S&P US TMI TR USD',
 'SIXS':'S&P US TMI TR USD',
 'PCIG':'MSCI ACWI Ex USA NR USD',
 'THNQ':'S&P 500 (TR) (1970)',
 'FBCG':'Russell 1000 TR USD',
 'FBCV':'Russell 1000 TR USD',
 'FLRG':'Russell 1000 TR USD',
 'FFLG':'Russell 1000 TR USD',
 'FMAG':'S&P 500 (TR) (1970)',
 'FPRO':'S&P 500 (TR) (1970)',
 'SXQG':'S&P 500 (TR) (1970)',
 'CVAR':'Russell 3000 TR USD',
 'FDV':'S&P 500 (TR) (1970)',
 'CLSM':'S&P 500 (TR) (1970)',
 'TDSB':'S&P 500 (TR) (1970)',
 'TDSC':'S&P 500 (TR) (1970)',
 'SUPP':'S&P 500 (TR) (1970)',
 'AMOM':'S&P 500 (TR) (1970)',
 'SIXH':'S&P 500 (TR) (1970)',
 'MUSQ':'MUSQ Global Music Industry TR USD',
 'FEPI':'Solactive FANG Innovation TR USD',
 'DVDN':'S&P 500 (TR) (1970)',
 'FELC':'S&P 500 (TR) (1970)',
 'BCUS':'S&P 500 (TR) (1970)',
 'EMOT':'S&P 500 (TR) (1970)',
 'CCNR':'Bloomberg US 1000 TR USD',
 'WCME':'MSCI EM NR USD',
 'FAI':'S&P 500 (TR) (1970)',
 'FEAC':'Russell 3000 TR USD',
 'FEMR':'MSCI EM NR USD',
 'FFEM':'MSCI EM NR USD',
 'AIRR':'S&P 500 (TR) (1970)',
 'FDRR':'Russell 1000 TR USD',
 'FDVV':'Russell 1000 TR USD',
 'FIDI':'MSCI World ex USA NR USD',
 'FDMO':'Russell 1000 TR USD',
 'FCOM':'S&P 500 (TR) (1970)',
 'FHLC':'S&P 500 (TR) (1970)',
 'FIDU':'S&P 500 (TR) (1970)',
 'FTEC':'S&P 500 (TR) (1970)',
 'FMAT':'S&P 500 (TR) (1970)',
 'FREL':'S&P 500 (TR) (1970)',
 'FUTY':'S&P 500 (TR) (1970)',
 'FSMD':'DJ US Total Stock Market TR USD',
 'FDEM':'MSCI EM NR USD',
 'FVAL':'Russell 1000 TR USD',
 'FPA':'Nasdaq Dev Market AP Ex Japan TR USD',
 'FTHI':'S&P 500 (TR) (1970)',
 'FTCS':'S&P 500 (TR) (1970)',
 'FCA':'NASDAQ China TR USD',
 'FXD':'Russell 1000 TR USD',
 'FXG':'Russell 3000 TR USD',
 'FDTS':'MSCI World ex USA NR USD',
 'FGD':'MSCI ACWI NR USD',
 'FDN':'S&P 500 (TR) (1970)',
 'FDM':'Russell 3000 TR USD',
 'FXN':'Russell 1000 TR USD',
 'FXO':'Russell 1000 TR USD',
 'FAN':'Russell 3000 TR USD',
 'FXH':'Russell 1000 TR USD',
 'FXR':'Russell 1000 TR USD',
 'FTRI':'Indxx Gbl Natural Resour Income TR USD',
 'FPXE':'MSCI Europe NR USD',
 'FEX':'S&P 500 (TR) (1970)',
 'FTC':'S&P 500 (TR) (1970)',
 'FTA':'S&P 500 (TR) (1970)',
 'FCTR':'NASDAQ US 500 Large Cap TR USD',
 'FXZ':'Russell 1000 TR USD',
 'FNX':'Russell 3000 TR USD',
 'FNK':'Russell 3000 TR USD',
 'FDL':'S&P 500 (TR) (1970)',
 'FAD':'Russell 3000 TR USD',
 'FAB':'Russell 3000 TR USD',
 'MDIV':'S&P 500 (TR) (1970)',
 'ROBT':'S&P 500 (TR) (1970)',
 'GRID':'Russell 3000 TR USD',
 'CIBR':'S&P 500 (TR) (1970)',
 'FTXR':'NASDAQ US Benchmark TR USD',
 'QQEW':'S&P 500 (TR) (1970)',
 'QQXT':'Russell 3000 TR USD',
 'QTEC':'S&P 500 (TR) (1970)',
 'FCG':'Russell 3000 TR USD',
 'EMLP':'S&P 500 (TR) (1970)',
 'FBT':'S&P 500 (TR) (1970)',
 'FID':'MSCI World ex USA NR USD',
 'FRI':'Russell 3000 TR USD',
 'FYX':'Russell 3000 TR USD',
 'FYC':'Russell 3000 TR USD',
 'FYT':'Russell 3000 TR USD',
 'FXL':'Russell 1000 TR USD',
 'FXU':'Russell 1000 TR USD',
 'FVD':'S&P 500 (TR) (1970)',
 'FIW':'Russell 3000 TR USD',
 'BNGE':'S-Network Streaming & Gaming USD',
 'MDEV':'Indxx Medical Devices NR USD',
 'EKG':'Russell 3000 TR USD',
 'FTDS':'S&P 500 (TR) (1970)',
 'RBLD':'Russell 3000 TR USD',
 'RDVI':'S&P 500 (TR) (1970)',
 'FTGS':'S&P 500 (TR) (1970)',
 'FQAL':'Russell 1000 TR USD',
 'FDLO':'Russell 1000 TR USD',
 'FDT':'NASDAQ DM Ex United States TR USD',
 'EDOW':'DJ Industrial Average TR USD',
 'FLN':'NASDAQ Latin America TR USD',
 'FNY':'Russell 3000 TR USD',
 'QABA':'Russell 3000 TR USD',
 'FTXL':'NASDAQ US Benchmark TR USD',
 'FPX':'S&P 500 (TR) (1970)',
 'MISL':'S&P 500 (TR) (1970)',
 'EMDM':'MSCI EM NR USD',
 'FTIF':'S&P 500 (TR) (1970)',
 'DOGG':'S&P 500 (TR) (1970)',
 'SDVD':'Russell 3000 TR USD',
 'TDVI':'S&P 500 (TR) (1970)',
 'FCFY':'S&P 500 (TR) (1970)',
 'FTHF':'MSCI EM NR USD',
 'FELG':'Russell 1000 TR USD',
 'FELV':'Russell 1000 TR USD',
 'FESM':'Russell 3000 TR USD',
 'FMDE':'Russell 3000 TR USD',
 'FFLV':'Russell 1000 Value TR USD',
 'FDND':'S&P 500 (TR) (1970)',
 'FBUF':'S&P 500 (TR)',
 'FHEQ':'S&P 500 (TR)',
 'FYEE':'S&P 500 (TR)',
 'BBSC':'Morningstar US Small TME NR USD',
 'BCHI':'MSCI ACWI Ex USA NR USD',
 'AFLG':'S&P 500 (TR) (1970)',
 'AFMC':'Russell 3000 TR USD',
 'AFSM':'Russell 3000 TR USD',
 'DVOL':'S&P 500 (TR) (1970)',
 'DVLU':'S&P 500 (TR) (1970)',
 'HUSV':'S&P 500 (TR) (1970)',
 'LEGR':'S&P 500 (TR) (1970)',
 'FTXO':'NASDAQ US Benchmark TR USD',
 'FTXG':'NASDAQ US Benchmark TR USD',
 'FTXN':'NASDAQ US Benchmark TR USD',
 'FTXH':'NASDAQ US Benchmark TR USD',
 'RFDI':'MSCI EAFE NR USD',
 'RFEM':'MSCI EM NR USD',
 'SDVY':'Russell 3000 TR USD',
 'HSMV':'S&P 1000 TR',
 'ILDR':'Russell 3000 TR USD',
 'XPND':'S&P 500 (TR) (1970)',
 'MMSC':'Russell 3000 TR USD',
 'LALT':'S&P 500 (TR) (1970)',
 'PRAY':'MSCI World NR USD',
 'CRPT':'S&P 500 (TR) (1970)',
 'EIPX':'S&P 500 (TR) (1970)',
 'EIPI':'S&P 500 (TR) (1970)',
 'BBUS':'Morningstar US TME TR USD',
 'ZAP':'S&P 500 (TR) (1970)',
 'UMMA':'MSCI ACWI Ex USA NR USD',
 'PCGG':'MSCI ACWI NR USD',
 'WDIV':'WisdomTree Global High Dividend TR USD',
 'BUYZ':'Russell 3000 TR USD',
 'FLAX':'FTSE AP ex Jpn, Aus and NZ NR USD',
 'FLBR':'FTSE Brazil NR USD',
 'FLCH':'FTSE China NR USD',
 'FLGR':'FTSE Germany (US RIC) NR USD',
 'FLIN':'FTSE India NR USD',
 'FLJP':'FTSE Japan NR USD',
 'FLJH':'FTSE Japan NR USD',
 'DHS':'WisdomTree US Equity Income UCITS NR USD',
 'TMAT':'MSCI ACWI NR USD',
 'DEM':'WisdomTree EM Equity Income UCITS TR USD',
 'FLLA':'FTSE Latin America NR USD',
 'FLKR':'FTSE Korea NR USD',
 'FLGB':'FTSE UK (US RIC) NR USD',
 'HELX':'Russell 3000 TR USD',
 'IQM':'Russell 3000 TR USD',
 'DAX':'MSCI EAFE NR USD',
 'GURU':'S&P 500 (TR) (1970)',
 'MILN':'S&P 500 (TR) (1970)',
 'MLPA':'S&P 500 (TR) (1970)',
 'ARGT':'MSCI EM NR USD',
 'CHIQ':'MSCI EM NR USD',
 'QDIV':'S&P 500 (TR) (1970)',
 'ALTY':'S&P 500 (TR) (1970)',
 'DIV':'S&P 500 (TR) (1970)',
 'PAVE':'S&P 500 (TR) (1970)',
 'CEFA':'MSCI EAFE NR USD',
 'ONOF':'S&P 500 (TR) (1970)',
 'XDAT':'Russell 3000 TR USD',
 'LOPP':'S&P 500 (TR) (1970)',
 'GGRW':'S&P 500 (TR) (1970)',
 'XTR':'S&P 500 (TR) (1970)',
 'QCLR':'S&P 500 (TR) (1970)',
 'QTR':'S&P 500 (TR) (1970)',
 'DIEM':'Morningstar EM Div Enh Sel NR USD',
 'XNAV':'S&P 500 (TR) (1970)',
 'GCAD':'S&P 500 (TR) (1970)',
 'FLEU':'FTSE Developed Eurozone (US RIC) NR USD',
 'FLTW':'FTSE Taiwan (US RIC) NR USD',
 'AUSF':'S&P 500 (TR) (1970)',
 'GABF':'S&P 500 (TR) (1970)',
 'INCM':'Russell 3000 TR USD',
 'FLOW':'S&P 500 (TR) (1970)',
 'BRAZ':'MSCI EM NR USD',
 'NDIA':'MSCI EM NR USD',
 'XRLX':'S&P 500 (TR) (1970)',
 'LDEM':'FTSE Em AC xCW xTC xREITS DG wQlt NR USD',
 'MNRS':'Indxx Bitcoin Miners TR USD',
 'GEM':'MSCI EM NR USD',
 'GSLC':'S&P 500 (TR) (1970)',
 'GSSC':'Russell 3000 TR USD',
 'GSEW':'S&P 500 (TR) (1970)',
 'GVIP':'S&P 500 (TR) (1970)',
 'JUST':'Russell 1000 TR USD',
 'HIPS':'S&P 500 (TR) (1970)',
 'MOTO':'MSCI World NR USD',
 'GSEE':'MSCI EM NR USD',
 'GSUS':'S&P 500 (TR) (1970)',
 'ADIV':'MSCI AC Asia Pac Ex JPN NR USD',
 'GUSA':'Russell 1000 TR USD',
 'TYLG':'S&P 500 (TR) (1970)',
 'WINN':'S&P 500 (TR) (1970)',
 'GSC':'Russell 3000 TR USD',
 'GSJY':'MSCI Japan NR USD',
 'EMM':'MSCI EM NR USD',
 'EMC':'MSCI EM NR USD',
 'GXUS':'MSCI World ex USA NR USD',
 'GPIX':'S&P 500 (TR) (1970)',
 'GGUS':'Russell 1000 TR USD',
 'GVUS':'Russell 1000 TR USD',
 'OAKM':'S&P 500 (TR) (1970)',
 'EFFE':'MSCI EM NR USD',
 'BEEX':'S&P 500 (TR) (1970)',
 'STNC':'S&P 500 (TR) (1970)',
 'EGGS':'S&P 500 (TR) (1970)',
 'EGGY':'S&P 500 (TR) (1970)',
 'EGGQ':'S&P 500 (TR) (1970)',
 'LGDX':'S&P 500 (TR)',
 'SMDX':'S&P Composite 1500 (TR) USD',
 'SPYV':'S&P Emg Plus High Yield Divi Arst NR USD',
 'SPYG':'S&P UK High Yield Dividend Arstcr TR USD',
 'EMDV':'S&P Emg Plus High Yield Divi Arst NR USD',
 'FNDA':'S&P 500 (TR) (1970)',
 'LOUP':'S&P 500 (TR) (1970)',
 'TTEQ':'MSCI ACWI NR USD',
 'UAPR':'S&P 500 (TR) (1970)',
 'UJUN':'S&P 500 (TR)',
 'UMAR':'S&P 500 (TR) (1970)',
 'TBUX':'Bloomberg US Agg Bond TR USD',
 'HFXI':'MSCI EAFE NR USD',
 'QAI':'Russell 3000 TR USD',
 'MNA':'MSCI World NR USD',
 'UMAY':'S&P 500 (TR) (1970)',
 'WISE':'MSCI ACWI NR USD',
 'SPUS':'S&P 500 (TR) (1970)',
 'IWFG':'Russell 3000 TR USD',
 'IWLG':'Russell 3000 TR USD',
 'HAPI':'S&P 500 (TR) (1970)',
 'IQSM':'Russell 3000 TR USD',
 'MEDI':'S&P 500 (TR) (1970)',
 'GDIV':'S&P 500 (TR) (1970)',
 'NACP':'Russell 1000 TR USD',
 'IQSU':'Russell 3000 TR USD',
 'SPXE':'S&P 500 Scored & Screened TR USD',
 'HFGO':'Russell 1000 TR USD',
 'MUU':'NASDAQ 100 TR USD',
 'HAPS':'S&P 500 (TR) (1970)',
 'CGRO':'Russell 1000 TR CAD',
 'WGMI':'S&P 500 (TR)',
 'AAPR':'S&P 500 (TR) (1970)',
 'QQA':'NASDAQ 100 TR USD',
 'RFLR':'Russell 2000 TR USD',
 'APOC':'S&P 500 (TR) (1970)',
 'QBIG':'NASDAQ Composite TR USD',
 'STCE':'MSCI ACWI NR USD',
 'PSR':'S&P 500 (TR) (1970)',
 'PPA':'S&P 500 (TR) (1970)',
 'PKW':'S&P 500 (TR) (1970)',
 'PFM':'Russell 3000 TR USD',
 'DJD':'S&P Composite 1500 TR USD',
 'PYZ':'NASDAQ Composite TR USD',
 'PJP':'S&P 500 (TR) (1970)',
 'PSI':'NASDAQ Composite TR USD',
 'PRF':'Russell 3000 TR USD',
 'PRFZ':'Russell 3000 TR USD',
 'PGJ':'MSCI China H NR USD',
 'PEY':'Russell 3000 TR USD',
 'PNQI':'NASDAQ Composite TR USD',
 'QQQ':'NASDAQ 100 TR USD',
 'PBP':'S&P 500 (TR) (1970)',
 'PHDG':'S&P 500 (TR) (1970)',
 'MAGA':'S&P 500 (TR) (1970)',
 'RSP':'S&P 500 (TR) (1970)',
 'SPGP':'S&P 500 GARP TR USD',
 'RPG':'S&P Composite 1500 TR USD',
 'RPV':'S&P Composite 1500 TR USD',
 'XLG':'S&P Composite 1500 TR USD',
 'SPVM':'S&P 500 (TR) (1970)',
 'RFG':'S&P Composite 1500 TR USD',
 'RFV':'S&P Composite 1500 TR USD',
 'XMMO':'S&P Composite 1500 TR USD',
 'XMVM':'S&P Composite 1500 TR USD',
 'RZG':'S&P Composite 1500 TR USD',
 'RZV':'S&P Composite 1500 TR USD',
 'XSMO':'S&P Composite 1500 TR USD',
 'XSVM':'S&P Composite 1500 (TR) USD',
 'CSD':'Russell 3000 TR USD',
 'PHO':'S&P 500 (TR) (1970)',
 'PBW':'Russell 3000 TR USD',
 'SFLR':'S&P 500 (TR) (1970)',
 'SPHQ':'S&P 500 (TR) (1970)',
 'XMHQ':'S&P Composite 1500 (TR) USD',
 'RSPS':'S&P 500 (TR) (1970)',
 'RSPD':'S&P 500 (TR) (1970)',
 'RSPF':'S&P 500 (TR) (1970)',
 'RSPG':'S&P 500 (TR) (1970)',
 'RSPH':'S&P 500 (TR) (1970)',
 'RSPM':'S&P 500 (TR) (1970)',
 'RSPN':'S&P 500 (TR) (1970)',
 'RSPR':'S&P 500 (TR) (1970)',
 'RSPT':'S&P 500 (TR) (1970)',
 'RSPU':'S&P 500 (TR) (1970)',
 'GGME':'NASDAQ Composite TR USD',
 'GRPM':'S&P Composite 1500 TR USD',
 'IGPT':'NASDAQ Composite TR USD',
 'KNCT':'NASDAQ Composite TR USD',
 'UPGD':'Russell 3000 TR USD',
 'KNO':'MSCI World Equal Weighted NR USD',
 'QQLV':'Nasdaq-100 Low Volatility TR USD',
 'KLMN':'MSCI Glb Climate 500 NA Selectn NR USD',
 'CQQQ':'MSCI China NR USD',
 'PEZ':'NASDAQ Composite TR USD',
 'PSL':'NASDAQ Composite TR USD',
 'PIZ':'MSCI EAFE NR USD',
 'PIE':'MSCI EM NR USD',
 'PFI':'NASDAQ Composite TR USD',
 'PTH':'NASDAQ Composite TR USD',
 'PRN':'NASDAQ Composite TR USD',
 'PDP':'NASDAQ Composite TR USD',
 'DWAS':'Russell 3000 TR USD',
 'PTF':'NASDAQ Composite TR USD',
 'PUI':'NASDAQ Composite TR USD',
 'PBE':'S&P 500 (TR) (1970)',
 'PKB':'S&P 500 (TR) (1970)',
 'PBJ':'S&P 500 (TR) (1970)',
 'PWB':'Russell 3000 TR USD',
 'PWV':'Russell 3000 TR USD',
 'PEJ':'S&P 500 (TR) (1970)',
 'PXJ':'S&P 500 (TR) (1970)',
 'PXF':'MSCI EAFE NR USD',
 'PDN':'MSCI World Ex USA IMI NR USD',
 'PXH':'MSCI EM NR USD',
 'KBWB':'S&P 500 (TR) (1970)',
 'KBWD':'S&P 500 (TR) (1970)',
 'KBWP':'S&P 500 (TR) (1970)',
 'PBUS':'MSCI USA GR USD',
 'IUS':'Russell 3000 TR USD',
 'OMFL':'Russell 3000 TR USD',
 'EQAL':'Russell 3000 TR USD',
 'SPHB':'S&P 500 (TR) (1970)',
 'SPMO':'S&P 500 (TR) (1970)',
 'RWL':'S&P 500 (TR) (1970)',
 'EELV':'MSCI EM NR USD',
 'EEMO':'MSCI EM NR USD',
 'CGW':'MSCI EAFE NR USD',
 'IDHQ':'MSCI EAFE NR USD',
 'RWK':'S&P Composite 1500 (TR) USD',
 'XMLV':'S&P Composite 1500 TR USD',
 'RWJ':'S&P Composite 1500 TR USD',
 'PSCD':'S&P Composite 1500 TR USD',
 'PSCC':'S&P Composite 1500 TR USD',
 'PSCE':'S&P Composite 1500 TR USD',
 'PSCF':'S&P Composite 1500 (TR) USD',
 'PSCH':'S&P Composite 1500 TR USD',
 'XSHD':'S&P Composite 1500 TR USD',
 'PSCI':'S&P Composite 1500 TR USD',
 'PSCT':'S&P Composite 1500 TR USD',
 'XSLV':'S&P Composite 1500 TR USD',
 'PSCM':'S&P Composite 1500 (TR) USD',
 'PSCU':'S&P Composite 1500 TR USD',
 'RDIV':'S&P Composite 1500 (TR) USD',
 'CZA':'Russell 3000 TR USD',
 'CVY':'S&P 500 (TR) (1970)',
 'QQQJ':'Russell 3000 TR USD',
 'QQQM':'Russell 3000 TR USD',
 'IMFL':'MSCI EAFE NR USD',
 'SOXQ':'NASDAQ Composite TR USD',
 'IBBQ':'NASDAQ Composite TR USD',
 'QVML':'S&P 500 (TR) (1970)',
 'QVMM':'S&P Composite 1500 TR USD',
 'QVMS':'S&P Composite 1500 TR USD',
 'QQMG':'NASDAQ Composite TR USD',
 'NXTE':'MSCI ACWI IMI NR USD',
 'QQQS':'Russell 2000 TR USD',
 'XSHQ':'S&P Composite 1500 TR USD',
 'PXI':'NASDAQ Composite TR USD',
 'PXE':'S&P 500 (TR) (1970)',
 'PIO':'MSCI EAFE NR USD',
 'KBWY':'S&P 500 (TR) (1970)',
 'OMFS':'Russell 3000 TR USD',
 'RSPE':'S&P 500 (TR) (1970)',
 'BMVP':'S&P 500 (TR) (1970)',
 'POWA':'S&P 500 (TR) (1970)',
 'RSPC':'S&P 500 (TR) (1970)',
 'DIVG':'S&P Composite 1500 TR USD',
 'QOWZ':'Nasdaq US Free CF Achievers TR USD',
 'GRPZ':'S&P SmallCap 600 GARP TR USD',
 'AIA':'S&P Developed Ex US BMI TR USD',
 'FXI':'FTSE Emerging All Cap TR USD',
 'AOA':'MSCI ACWI NR USD',
 'IVV':'S&P US TMI TR USD',
 'IJR':'S&P US TMI TR USD',
 'USRT':'Russell 3000 TR USD',
 'IYY':'S&P US TMI TR USD',
 'EEMV':'MSCI EM NR USD',
 'DVYE':'S&P Emerging BMI TR USD',
 'IOO':'S&P Global BMI NR USD',
 'ICLN':'S&P Global BMI NR USD',
 'INDY':'MSCI EM NR USD',
 'IDV':'S&P Developed Ex US BMI TR USD',
 'ILF':'S&P Emerging BMI NR USD',
 'AAXJ':'MSCI EM NR USD',
 'EPU':'MSCI EM NR USD',
 'EWZ':'MSCI EM NR USD',
 'BKF':'MSCI EM NR USD',
 'ECH':'MSCI EM NR USD',
 'ECNS':'MSCI EM NR USD',
 'EEMA':'MSCI EM NR USD',
 'EEM':'MSCI EM NR USD',
 'EEMS':'MSCI EM NR USD',
 'DSI':'MSCI USA NR USD',
 'EWY':'MSCI EM NR USD',
 'SUSA':'MSCI USA NR USD',
 'IBB':'MSCI USA NR USD',
 'REZ':'Russell 3000 TR USD',
 'IWD':'Russell 3000 TR USD',
 'IWM':'Russell 3000 TR USD',
 'IWV':'Russell 3000 TR USD',
 'DVY':'S&P US TMI TR USD',
 'IYM':'Russell 3000 TR USD',
 'IYK':'Russell 3000 TR USD',
 'IYC':'Russell 3000 TR USD',
 'IYE':'Russell 3000 TR USD',
 'IYG':'S&P US TMI TR USD',
 'IYF':'Russell 3000 TR USD',
 'IYH':'Russell 3000 TR USD',
 'IYJ':'Russell 3000 TR USD',
 'IDU':'Russell 3000 TR USD',
 'ILCB':'Morningstar US Market TR USD',
 'ILCG':'Morningstar US Market TR USD',
 'ILCV':'Morningstar US Market TR USD',
 'IMCB':'Morningstar US Market TR USD',
 'IMCG':'Morningstar US Market TR USD',
 'ISCB':'Morningstar US Market TR USD',
 'ISCG':'Morningstar US Market TR USD',
 'IMCV':'Morningstar US Market TR USD',
 'DVYA':'S&P Developed Ex US BMI TR USD',
 'ICF':'S&P US TMI TR USD',
 'IJH':'S&P US TMI TR USD',
 'EUSA':'MSCI USA Equal Weighted GR USD',
 'IYT':'S&P US TMI TR USD',
 'IYW':'Russell 3000 TR USD',
 'ISCV':'Morningstar US Market TR USD',
 'EVLU':'MSCI Emg Mrkt Value Factor St NR USD',
 'ICVT':'Bloomberg US Universal TR USD',
 'DGRO':'Morningstar US Market TR USD',
 'HDV':'Morningstar US Market TR USD',
 'IEMG':'MSCI EM NR USD',
 'EFAV':'MSCI ACWI NR USD',
 'SMMV':'MSCI USA GR USD',
 'EMGF':'S&P Emerging BMI TR USD',
 'LRGF':'S&P US TMI TR USD',
 'SMLF':'S&P US TMI TR USD',
 'MTUM':'MSCI USA NR USD',
 'SIZE':'MSCI USA NR USD',
 'VLUE':'MSCI USA NR USD',
 'SUSL':'MSCI USA GR USD',
 'REET':'FTSE All World TR USD',
 'IYLD':'Bloomberg US Universal TR USD',
 'REM':'Russell 3000 TR USD',
 'MCHI':'MSCI EM NR USD',
 'EWT':'MSCI EM NR USD',
 'ESGU':'MSCI USA GR USD',
 'ESML':'MSCI USA GR USD',
 'DIVB':'Morningstar US Market TR USD',
 'IFRA':'MSCI USA NR USD',
 'TECB':'ICE US 3000 TR USD',
 'USXF':'MSCI USA GR USD',
 'EMXF':'MSCI EM NR USD',
 'SVAL':'Russell 3000 TR USD',
 'ESMV':'MSCI USA GR USD',
 'TCHI':'MSCI EM NR USD',
 'EFRA':'FTSE All World NR USD',
 'ERET':'FTSE All World TR USD',
 'EGUS':'MSCI USA GR USD',
 'EVUS':'MSCI USA GR USD',
 'QUAL':'MSCI USA GR USD',
 'IETC':'S&P US TMI TR USD',
 'GLOF':'S&P Global BMI TR USD',
 'USCL':'MSCI USA GR USD',
 'ICOP':'STOXX Emerging Markets All Cap NR USD',
 'ILIT':'STOXX Emerging Markets All Cap NR USD',
 'JADE':'MSCI EM NR USD',
 'MADE':'S&P Total Market TR USD',
 'SMAX':'Cboe S&P 500 Half BuyWrite NR USD',
 'AQLT':'MSCI ACWI Quality NR USD',
 'JHEM':'MSCI EM NR USD',
 'BBJP':'Morningstar Japan TME NR USD',
 'BBRE':'MSCI USA NR USD',
 'JPUS':'Russell 1000 TR USD',
 'JPME':'Russell 3000 TR USD',
 'JPSE':'Russell 3000 TR USD',
 'JMOM':'Russell 1000 TR USD',
 'JVAL':'Russell 1000 TR USD',
 'JEPI':'S&P 500 (TR)',
 'BBMC':'Morningstar US Market TR USD',
 'JEPQ':'NASDAQ 100 TR USD',
 'JMEE':'S&P Composite 1500 TR USD',
 'JPRE':'S&P 500 (TR)',
 'JQUA':'Russell 1000 TR USD',
 'LCDS':'S&P 500 (TR) (1970)',
 'MCDS':'Russell Mid Cap TR USD',
 'SCDS':'Russell 2000 TR USD',
 'JPIN':'FTSE Developed ex North America NR USD',
 'KTEC':'MSCI China All Shares NR USD',
 'JPSV':'Russell 3000 TR USD',
 'JCHI':'MSCI China All Shares NR USD',
 'BBEM':'Morningstar EM TME NR USD',
 'RUNN':'S&P 500 (TR) (1970)',
 'JPEF':'S&P 500 (TR) (1970)',
 'JGLO':'MSCI World NR USD',
 'IRTR':'Bloomberg US Agg Bond TR USD',
 'ITDB':'Russell 1000 TR USD',
 'ITDC':'Russell 1000 TR USD',
 'ITDD':'Russell 1000 TR USD',
 'ITDE':'Russell 1000 TR USD',
 'ITDF':'Russell 1000 TR USD',
 'ITDG':'Russell 1000 TR USD',
 'ITDH':'Russell 1000 TR USD',
 'ITDI':'Russell 1000 TR USD',
 'JTEK':'S&P 500 (TR) (1970)',
 'JDOC':'MSCI World NR USD',
 'JDVI':'MSCI EAFE NR USD',
 'IVVW':'S&P US TMI TR USD',
 'IWMW':'Russell 3000 TR USD',
 'IBAT':'STOXX Gbl Energy Storage Materials USD',
 'KHPI':'S&P 500 (TR) (1970)',
 'NBET':'S&P 500 (TR) (1970)',
 'PEPS':'S&P 500 (TR) (1970)',
 'MSLC':'Russell 1000 TR USD',
 'MSSM':'Russell 3000 TR USD',
 'LEXI':'S&P 500 (TR) (1970)',
 'LST':'S&P Composite 1500 (TR) USD',
 'CCOR':'S&P 500 (TR) (1970)',
 'KNOW':'S&P 500 (TR) (1970)',
 'RODM':'MSCI World ex USA NR USD',
 'ROAM':'MSCI EM NR USD',
 'ROSC':'Russell 3000 TR USD',
 'ROUS':'Russell 1000 TR USD',
 'KEMX':'MSCI EM NR USD',
 'LCR':'S&P 500 (TR) (1970)',
 'OVL':'S&P 500 (TR) (1970)',
 'VNSE':'S&P 500 (TR) (1970)',
 'INFL':'S&P 500 (TR) (1970)',
 'SPRX':'S&P 500 (TR) (1970)',
 'TUG':'S&P 500 (TR)',
 'MCH':'MSCI China NR USD',
 'MINV':'MSCI AC Asia Ex Japan NR USD',
 'HDUS':'Russell 1000 TR USD',
 'MEMX':'MSCI EM ex China NR USD',
 'NVIR':'S&P 500 (TR) (1970)',
 'CDEI':'Russell 1000 TR USD',
 'CVIE':'MSCI World ex USA NR USD',
 'SAEF':'S&P 500 (TR) (1970)',
 'CVLC':'Russell 1000 TR USD',
 'NBDS':'Russell 3000 TR USD',
 'MEM':'MSCI EM NR USD',
 'BCDF':'S&P 500 (TR) (1970)',
 'CVMC':'S&P 500 (TR) (1970)',
 'HQGO':'Russell 1000 TR USD',
 'LSGR':'S&P 500 (TR) (1970)',
 'BDVG':'Russell 1000 TR USD',
 'MKOR':'MSCI Korea 25-50 NR USD',
 'DIVL':'S&P 500 (TR) (1970)',
 'ADVE':'MSCI AC Asia Pacific NR USD',
 'ASIA':'MSCI AC Asia Ex Japan NR USD',
 'EMSF':'MSCI EM NR USD',
 'PAPI':'S&P 500 (TR) (1970)',
 'PHEQ':'S&P 500 (TR) (1970)',
 'VMAX':'Russell 1000 TR USD',
 'GQI':'S&P 500 (TR) (1970)',
 'MEMS':'MSCI EM NR USD',
 'EVLN':'Bloomberg US Universal TR USD',
 'TOGA':'Morningstar DM GR USD',
 'DUKQ':'Morningstar US Market TR USD',
 'DUKX':'Morningstar Global Markets xUS NR USD',
 'CPAI':'S&P 1000 TR',
 'QQH':'NASDAQ 100 TR USD',
 'LGH':'S&P 500 (TR) (1970)',
 'BLES':'S&P Global 1200 PR',
 'WWJD':'S&P International 700 TR USD',
 'ISMD':'Russell 2000 TR USD',
 'SECT':'S&P 500 (TR) (1970)',
 'NUEM':'MSCI EM NR USD',
 'NULG':'MSCI USA NR USD',
 'NULV':'MSCI USA NR USD',
 'NUMG':'MSCI USA NR USD',
 'NUMV':'MSCI USA NR USD',
 'NUSC':'MSCI USA NR USD',
 'NURE':'S&P 500 (TR) (1970)',
 'PTLC':'S&P 500 (TR) (1970)',
 'PTMC':'S&P Composite 1500 TR USD',
 'MRSK':'S&P 500 (TR) (1970)',
 'RISN':'S&P Target Risk Moderate TR USD',
 'GLRY':'S&P Composite 1500 TR USD',
 'FFND':'MSCI ACWI NR USD',
 'NUGO':'Russell 1000 TR USD',
 'FDLS':'MSCI ACWI NR USD',
 'BUYW':'S&P 500 (TR) (1970)',
 'PJFG':'S&P 500 (TR) (1970)',
 'NULC':'MSCI USA NR USD',
 'NUDV':'MSCI USA NR USD',
 'BAMD':'S&P 500 (TR) (1970)',
 'BAMG':'S&P 500 Growth TR USD',
 'BAMV':'S&P 500 Value TR USD',
 'BAMY':'Bloomberg US Agg Bond TR USD',
 'NSI':'MSCI EM NR USD',
 'PJFM':'Russell Mid Cap TR USD',
 'MDPL':'DJ Industrial Average TR USD',
 'MVFD':'S&P Composite 1500 (TR) USD',
 'PTL':'S&P 500 (TR) (1970)',
 'PRCS':'S&P 500 (TR) (1970)',
 'PRVS':'Russell 1000 Value TR USD',
 'KEMQ':'MSCI EM NR USD',
 'USAI':'S&P 500 (TR) (1970)',
 'SRVR':'FTSE Nareit All Equity REITs TR USD',
 'ICOW':'MSCI World NR USD',
 'ECOW':'FTSE Emerging Markets TR USD',
 'PTIN':'S&P Developed Ex-US Large Cap TR USD',
 'PTEU':'FTSE Eurozone TR USD',
 'COWZ':'S&P Composite 1500 TR USD',
 'BUL':'S&P 500 (TR) (1970)',
 'CALF':'Russell 2000 TR USD',
 'PWS':'S&P 500 (TR) (1970)',
 'MFEM':'MSCI EM NR USD',
 'MFUS':'S&P 500 (TR) (1970)',
 'RAFE':'S&P 500 (TR) (1970)',
 'PSET':'S&P 500 Growth TR USD',
 'PY':'S&P 500 Value TR USD',
 'UFO':'S&P 500 (TR) (1970)',
 'TOLZ':'S&P Global 1200 TR',
 'EHLS':'S&P 500 (TR)',
 'BTGD':'S&P 500 (TR)',
 'SPYT':'MSCI Europe Com Services 35/20 Cap NR',
 'EQRR':'NASDAQ Composite TR USD',
 'SPYC':'MSCI Europe Consumer Stap 35/20 Cap NR',
 'ONLN':'S&P Global 1200 TR',
 'SMDV':'Russell 3000 TR USD',
 'SPXN':'S&P 500 (TR) (1970)',
 'SPXV':'S&P 500 (TR) (1970)',
 'REGL':'S&P Composite 1500 (TR) USD',
 'ALTL':'S&P 500 (TR) (1970)',
 'PALC':'S&P 500 (TR) (1970)',
 'PAMC':'S&P Composite 1500 TR USD',
 'QDPL':'S&P 500 (TR) (1970)',
 'SUPL':'S&P Global 1200 TR',
 'ODDS':'S&P Global 1200 TR',
 'BYRE':'FTSE Nareit All Equity REITs TR USD',
 'BUYO':'Russell 3000 TR USD',
 'ION':'S&P Global 1200 TR',
 'COWG':'Russell 1000 TR USD',
 'INDS':'FTSE Nareit All Equity REITs TR USD',
 'MFDX':'RAFI Dynamic MF Dev ex-U.S. TR USD',
 'PSC':'Russell 2000 TR USD',
 'ISPY':'S&P 500 (TR) (1970)',
 'BCHP':'Russell 1000 Growth TR USD',
 'CAML':'S&P 500 (TR) (1970)',
 'CSMD':'S&P 500 (TR) (1970)',
 'IQQQ':'Nasdaq-100 Daily Covered Call TR USD',
 'ITWO':'Cboe Russell 2000 Daily Cvrd Call GR USD',
 'MAXJ':'S&P 500 (TR)',
 'CGDV':'S&P 500 (TR) (1970)',
 'CGUS':'S&P 500 (TR) (1970)',
 'HDG':'S&P 500 (TR) (1970)',
 'CSM':'S&P 500 (TR) (1970)',
 'MRGR':'S&P US TMI TR USD',
 'TMDV':'Russell 3000 TR USD',
 'NOBL':'S&P 500 (TR) (1970)',
 'TDV':'S&P Composite 1500 (TR) USD',
 'UYM':'S&P 500 (TR) (1970)',
 'UGE':'S&P 500 (TR) (1970)',
 'UCC':'S&P 500 (TR) (1970)',
 'DDM':'S&P 500 (TR) (1970)',
 'UYG':'S&P 500 (TR) (1970)',
 'UXI':'S&P 500 (TR) (1970)',
 'BIB':'NASDAQ Composite TR USD',
 'QLD':'NASDAQ Composite TR USD',
 'URE':'S&P Real Estate Select Sector TR USD',
 'UWM':'Russell 3000 TR USD',
 'SSO':'S&P 500 (TR) (1970)',
 'USD':'S&P 500 (TR) (1970)',
 'SAA':'S&P Composite 1500 (TR) USD',
 'ROM':'S&P Technology Select Sector TR USD',
 'LTL':'S&P Cmmncton Svces Select Sector TR USD',
 'UPW':'S&P Utilities Select Sector TR USD',
 'UDOW':'S&P 500 (TR) (1970)',
 'TQQQ':'NASDAQ Composite TR USD',
 'URTY':'Russell 3000 TR USD',
 'UPRO':'S&P 500 (TR) (1970)',
 'ANEW':'S&P Global 1200 TR',
 'SKYU':'NASDAQ Composite TR USD',
 'PGRO':'Russell 3000 TR USD',
 'QQQA':'NASDAQ Composite TR USD',
 'CTEX':'S&P US TMI TR USD',
 'DAT':'S&P Global 1200 TR',
 'MAKX':'S&P US TMI TR USD',
 'OND':'S&P Global 1200 TR',
 'TINT':'S&P Global 1200 TR',
 'TINY':'S&P Global 1200 TR',
 'TMFG':'FTSE Global All Cap NR USD',
 'TMFM':'Russell 3000 TR USD',
 'TMFE':'S&P 500 (TR) (1970)',
 'TMFS':'Russell 3000 TR USD',
 'TMFX':'Russell 3000 TR USD',
 'RXL':'S&P 500 (TR) (1970)',
 'PWER':'MSCI ACWI NR USD',
 'NANC':'S&P 500 (TR) (1970)',
 'OZEM':'Solactive GBS Global Mkt All Cap TR USD',
 'QQQH':'NASDAQ Composite TR USD',
 'ULTY':'S&P 500 (TR) (1970)',
 'IPO':'S&P 500 (TR) (1970)',
 'RWO':'MSCI ACWI Ex USA NR USD',
 'DIA':'DJ Industrial Average TR USD',
 'RWR':'S&P 500 (TR) (1970)',
 'XITK':'S&P 500 (TR) (1970)',
 'CWI':'MSCI ACWI IMI NR USD',
 'XNTK':'S&P 500 (TR) (1970)',
 'SPGM':'MSCI ACWI Ex USA NR USD',
 'SPTM':'S&P 500 (TR) (1970)',
 'SPMD':'S&P 500 (TR) (1970)',
 'VLU':'S&P 500 (TR) (1970)',
 'MDYV':'S&P 500 (TR) (1970)',
 'SLYG':'S&P 500 (TR) (1970)',
 'SLYV':'S&P 500 (TR) (1970)',
 'XAR':'S&P 500 (TR) (1970)',
 'KBE':'S&P 500 (TR) (1970)',
 'XBI':'S&P 500 (TR) (1970)',
 'KCE':'S&P 500 (TR) (1970)',
 'SDY':'S&P 500 (TR) (1970)',
 'GII':'MSCI ACWI IMI NR USD',
 'GNR':'MSCI ACWI IMI NR USD',
 'XHE':'S&P 500 (TR) (1970)',
 'XHS':'S&P 500 (TR) (1970)',
 'XHB':'S&P 500 (TR) (1970)',
 'XME':'S&P 500 (TR) (1970)',
 'MDY':'S&P MidCap 400 TR',
 'NANR':'MSCI ACWI IMI NR USD',
 'XOP':'S&P 500 (TR) (1970)',
 'XPH':'S&P 500 (TR) (1970)',
 'KRE':'S&P 500 (TR) (1970)',
 'XRT':'S&P 500 (TR) (1970)',
 'XSD':'S&P 500 (TR) (1970)',
 'XSW':'S&P 500 (TR) (1970)',
 'XTL':'S&P 500 (TR) (1970)',
 'XTN':'S&P 500 (TR) (1970)',
 'NZAC':'MSCI ACWI Ex USA NR USD',
 'SPYI':'S&P 500 (TR) (1970)',
 'QWLD':'MSCI ACWI Ex USA NR USD',
 'MDYG':'S&P 500 (TR) (1970)',
 'KIE':'S&P 500 (TR) (1970)',
 'XES':'S&P 500 (TR) (1970)',
 'EFIV':'S&P 500 (TR) (1970)',
 'SPDG':'S&P Sector-Neutral HY Div Aristcr TR USD',
 'QQQI':'NASDAQ 100 TR USD',
 'SPIN':'S&P 500 (TR) (1970)',
 'TEKX':'MSCI ACWI NR USD',
 'QIDX':'S&P 500 (TR)',
 'RILA':'S&P 500 (TR)',
 'ELM':'MSCI ACWI IMI NR USD',
 'SCAP':'S&P 500 (TR) (1970)',
 'XLC':'S&P 500 (TR) (1970)',
 'XLY':'S&P 500 (TR) (1970)',
 'XLP':'S&P 500 (TR) (1970)',
 'XLE':'S&P 500 (TR) (1970)',
 'XLF':'S&P 500 (TR) (1970)',
 'XLV':'S&P 500 (TR) (1970)',
 'XLI':'S&P 500 (TR) (1970)',
 'XLB':'S&P 500 (TR) (1970)',
 'FNDE':'MSCI EM NR USD',
 'FNDF':'MSCI EAFE NR USD',
 'FNDC':'MSCI EAFE NR USD',
 'FNDB':'Russell 3000 TR USD',
 'FNDX':'Russell 1000 TR USD',
 'SCHB':'DJ US Broad Stock Market TR USD',
 'SCHX':'S&P 500 (TR) (1970)',
 'SCHG':'S&P 500 (TR) (1970)',
 'CNRG':'S&P 500 (TR) (1970)',
 'ROKT':'S&P 500 (TR) (1970)',
 'QUS':'S&P 500 (TR) (1970)',
 'SPSM':'S&P 500 (TR) (1970)',
 'ONEV':'S&P 500 (TR) (1970)',
 'ONEO':'S&P 500 (TR) (1970)',
 'MMTM':'S&P 500 (TR) (1970)',
 'FITE':'S&P 500 (TR) (1970)',
 'SIMS':'S&P 500 (TR) (1970)',
 'KOMP':'S&P 500 (TR) (1970)',
 'HAIL':'S&P 500 (TR) (1970)',
 'SHE':'S&P 500 (TR) (1970)',
 'LGLV':'S&P 500 (TR) (1970)',
 'XLSR':'S&P 500 (TR) (1970)',
 'SMLV':'S&P 500 (TR) (1970)',
 'XLK':'S&P 500 (TR) (1970)',
 'XLRE':'S&P 500 (TR) (1970)',
 'XLU':'S&P 500 (TR) (1970)',
 'SPD':'S&P 500 (TR) (1970)',
 'SCHY':'MSCI EAFE NR USD',
 'SPBC':'S&P 500 (TR) (1970)',
 'PINK':'S&P 500 (TR) (1970)',
 'HEQT':'Bloomberg US EQ:FI 60:40 TR USD',
 'ICAP':'S&P 500 (TR) (1970)',
 'CDX':'Bloomberg Capital U.S. Aggregate TR USD',
 'ADPV':'S&P 500 (TR) (1970)',
 'SURI':'S&P 500 (TR) (1970)',
 'SCHK':'Russell 1000 TR USD',
 'SCHF':'MSCI EAFE NR USD',
 'SCHH':'S&P 500 (TR) (1970)',
 'TESL':'S&P 500 (TR) (1970)',
 'USSE':'Russell 3000 TR USD',
 'SPTE':'S&P 500 (TR) (1970)',
 'SPWO':'S&P 500 (TR) (1970)',
 'NXTI':'Next Intangible Core TR USD',
 'LIMI':'BITA Gbl Lith and Bat Metals Sel NR USD',
 'URAN':'BITA Gbl Uranium & Nuclear Select NR USD',
 'SSUS':'S&P 500 (TR) (1970)',
 'SGDM':'S&P 500 (TR) (1970)',
 'SGDJ':'S&P 500 (TR) (1970)',
 'HNDL':'Bloomberg US Agg Bond TR USD',
 'ROMO':'S&P Target Risk Balanced TR USD',
 'TCHP':'Russell 3000 TR USD',
 'TEQI':'Russell 3000 TR USD',
 'TGRW':'Russell 3000 TR USD',
 'AGOX':'MSCI ACWI NR USD',
 'TSPA':'Russell 3000 TR USD',
 'RHRX':'S&P 500 (TR) (1970)',
 'RHTX':'Morningstar US Total Market TR USD',
 'LITP':'S&P 500 (TR) (1970)',
 'TDVG':'Russell 3000 TR USD',
 'AMAX':'Bloomberg Capital U.S. Aggregate TR USD',
 'CANC':'S&P 500 (TR)',
 'TOLL':'S&P 500 (TR)',
 'TCAF':'Russell 3000 TR USD',
 'TGRT':'Russell 3000 TR USD',
 'TMSL':'Russell 3000 TR USD',
 'TVAL':'Russell 3000 TR USD',
 'TXS':'VettaFi US Equity 3000 NR USD',
 'HRTS':'S&P 500 (TR)',
 'SMCF':'S&P 500 (TR) (1970)',
 'OILT':'VettaFi US Equity 300 USD',
 'COPP':'S&P 500 (TR) (1970)',
 'EAGL':'S&P 500 (TR) (1970)',
 'BOTT':'Solactive Industrial Robotics & Atmtn',
 'AGMI':'STOXX Global Silver Mining TR USD',
 'RSSY':'S&P 500 (TR) (1970)',
 'RSBA':'S&P 500 (TR) (1970)',
 'ACSI':'S&P 500 (TR) (1970)',
 'RPAR':'S&P 500 (TR) (1970)',
 'JSTC':'DJ Global TR USD',
 'GSPY':'S&P 500 (TR) (1970)',
 'SPRE':'S&P 500 (TR) (1970)',
 'BOAT':'S&P 500 (TR)',
 'UPAR':'S&P 500 (TR) (1970)',
 'HAUS':'S&P 500 (TR)',
 'TIME':'S&P 500 (TR) (1970)',
 'GVLU':'Russell 1000 TR USD',
 'AZTD':'S&P 500 (TR) (1970)',
 'CCSO':'S&P 500 (TR) (1970)',
 'TSME':'Russell 3000 TR USD',
 'GIAX':'S&P 500 (TR) (1970)',
 'FCUS':'Russell 1000 TR USD',
 'NRSH':'S&P 500 (TR) (1970)',
 'REAI':'S&P 500 (TR)',
 'TFPN':'S&P 500 (TR) (1970)',
 'SMCO':'Russell 2500 TR USD',
 'ABFL':'Russell 3000 TR USD',
 'ABLD':'S&P 500 (TR) (1970)',
 'ABOT':'S&P 500 (TR) (1970)',
 'TSEL':'Bloomberg US 3000 TR USD',
 'ABLS':'S&P 500 (TR) (1970)',
 'WLDR':'MSCI World NR USD',
 'LSAF':'S&P 500 (TR) (1970)',
 'TPHD':'S&P 500 (TR) (1970)',
 'TPLC':'S&P 500 (TR) (1970)',
 'TPSC':'Russell 3000 TR USD',
 'LSAT':'S&P 500 (TR) (1970)',
 'DVND':'Bloomberg US 3000 TR USD',
 'LCF':'Bloomberg US 3000 TR USD',
 'WCEO':'S&P SmallCap 600 TR USD',
 'BINV':'MSCI EAFE NR USD',
 'BSMC':'Russell 3000 TR USD',
 'BUSA':'Russell 1000 TR USD',
 'TDI':'Bloomberg World ex-US Large-Mid TR USD',
 'OASC':'Bloomberg US 2500 TR USD',
 'ISRA':'MSCI ACWI NR USD',
 'DURA':'S&P 500 (TR) (1970)',
 'MOTI':'MSCI ACWI NR USD',
 'MOAT':'S&P 500 (TR) (1970)',
 'MORT':'S&P 500 (TR) (1970)',
 'LFEQ':'S&P 500 (TR) (1970)',
 'VIG':'DJ US Total Stock Market TR USD',
 'VSGX':'FTSE Global All Cap ex US TR USD',
 'VEA':'FTSE Global All Cap ex US TR USD',
 'VYM':'DJ US Total Stock Market TR USD',
 'VIGI':'S&P Global Ex US BMI TR USD',
 'VOOG':'DJ US Total Stock Market TR USD',
 'VOOV':'DJ US Total Stock Market TR USD',
 'IVOO':'DJ US Total Stock Market TR USD',
 'IVOV':'DJ US Total Stock Market TR USD',
 'VIOG':'DJ US Total Stock Market TR USD',
 'VIOO':'DJ US Total Stock Market TR USD',
 'VIOV':'DJ US Total Stock Market TR USD',
 'VXUS':'FTSE Global All Cap ex US (USA) NR USD',
 'VT':'FTSE Global All Cap (US RIC) NR USD',
 'VFMV':'Russell 3000 TR USD',
 'VFMO':'Russell 3000 TR USD',
 'VFVA':'Russell 3000 TR USD',
 'MGMT':'S&P 500 (TR) (1970)',
 'OALC':'S&P 500 (TR) (1970)',
 'OAEM':'MSCI EM NR USD',
 'QVOY':'MSCI World NR USD',
 'EQTY':'S&P 500 (TR) (1970)',
 'VFQY':'Russell 3000 TR USD',
 'ESGV':'DJ US Total Stock Market TR USD',
 'IVOG':'DJ US Total Stock Market TR USD',
 'UDI':'S&P 500 (TR) (1970)',
 'VPLS':'Bloomberg US Universal TR USD',
 'VCRB':'Bloomberg US Agg Float Adj TR USD',
 'MVAL':'Morningstar US Brd Val WMF TR USD',
 'MDST':'S&P 500 (TR) (1970)',
 'WEEI':'S&P 500 (TR) (1970)',
 'GFLW':'Victory Free Cash Flow Growth TR USD',
 'VCR':'MSCI US Investable Market 2500 NR USD',
 'VDC':'MSCI US Investable Market 2500 GR USD',
 'VDE':'MSCI US Investable Market 2500 GR USD',
 'VXF':'DJ US Total Stock Market TR USD',
 'VFH':'MSCI US Investable Market 2500 NR USD',
 'VEU':'FTSE Global All Cap ex US (USA) NR USD',
 'GEND':'Solactive Equileap Gbl Gender Eqa NR USD',
 'FFOG':'Russell 3000 TR USD',
 'SPUC':'S&P 500 (TR) (1970)',
 'YALL':'S&P 500 (TR) (1970)',
 'XSOE':'WisdomTree EM xSt-Own Ent ESG Scr USD',
 'MDLV':'Solactive GBS United States 1000 TR USD',
 'ECML':'S&P 500 (TR)',
 'OPTZ':'S&P 500 (TR)',
 'CGGR':'S&P 500 (TR)',
 'XDSQ':'S&P 500 (TR) (1970)',
 'KONG':'S&P 500 (TR)',
 'XTJL':'S&P 500 (TR) (1970)',
 'FSCS':'Russell 3000 TR USD',
 'FTCE':'S&P 500 (TR)',
 'FSGS':'Russell 3000 TR USD',
 'RNEM':'MSCI EM NR USD',
 'KNGZ':'S&P 500 (TR)',
 'SHRY':'S&P 500 (TR)',
 'RND':'S&P 500 (TR)',
 'XUDV':'VettaFi New Front U.S. Div Select TR USD',
 'FLQL':'Russell 3000 TR USD',
 'FLQM':'Russell 3000 TR USD',
 'FLQS':'Russell 3000 TR USD',
 'UDIV':'Morningstar US Div Enh Sel NR USD',
 'USPX':'Morningstar US TME TR USD',
 'DVAL':'Russell 3000 TR USD',
 'INCE':'Russell 3000 TR USD',
 'PPI':'MSCI ACWI NR USD',
 'WUGI':'S&P 500 (TR)',
 'ITOT':'S&P US TMI TR USD',
 'RXI':'S&P Global BMI NR USD',
 'KXI':'S&P Global BMI NR USD',
 'IXC':'S&P Global BMI NR USD',
 'IXG':'S&P Global BMI NR USD',
 'IXJ':'S&P Global BMI NR USD',
 'IGF':'S&P Global BMI NR USD',
 'MXI':'S&P Global BMI NR USD',
 'IXN':'S&P Global BMI NR USD',
 'IXP':'S&P Global BMI NR USD',
 'WOOD':'S&P Global BMI NR USD',
 'JXI':'S&P Global BMI NR USD',
 'IWC':'Russell 3000 TR USD',
 'IGE':'S&P Global BMI NR USD',
 'IGM':'S&P Total Market TR USD',
 'IDGT':'S&P US TMI TR USD',
 'IGV':'S&P Total Market TR USD',
 'IWB':'Russell 3000 TR USD',
 'IWF':'Russell 3000 TR USD',
 'IWO':'Russell 3000 TR USD',
 'IWN':'Russell 3000 TR USD',
 'IWP':'Russell 3000 TR USD',
 'IWS':'Russell 3000 TR USD',
 'IWL':'Russell 3000 TR USD',
 'IWY':'Russell 3000 TR USD',
 'IWX':'Russell 3000 TR USD',
 'OEF':'S&P US TMI TR USD',
 'IVW':'S&P US TMI TR USD',
 'IVE':'S&P US TMI TR USD',
 'IJK':'S&P US TMI TR USD',
 'IJJ':'S&P US TMI TR USD',
 'IJT':'S&P US TMI TR USD',
 'IJS':'S&P US TMI TR USD',
 'ITA':'S&P US TMI TR USD',
 'ITB':'S&P US TMI TR USD',
 'IAK':'S&P US TMI TR USD',
 'IHI':'S&P US TMI TR USD',
 'IEO':'S&P US TMI TR USD',
 'IEZ':'S&P US TMI TR USD',
 'IHE':'S&P US TMI TR USD',
 'IYR':'S&P US TMI TR USD',
 'IAT':'S&P US TMI TR USD',
 'IYZ':'Russell 3000 TR USD',
 'IAI':'S&P US TMI TR USD',
 'IHF':'S&P US TMI TR USD',
 'SOXX':'MSCI USA NR USD',
 'GARP':'MSCI USA GR USD',
 'XJH':'S&P US TMI TR USD',
 'XJR':'S&P US TMI TR USD',
 'XVV':'S&P US TMI TR USD',
 'SMMD':'Russell 3000 TR USD',
 'AGIX':'Solactive Etna Artifi Gnrl Intel TR USD',
 'TOPT':'S&P US TMI TR USD',
 'JSML':'Russell 3000 TR USD',
 'JHML':'Russell 1000 TR USD',
 'JHMM':'Russell 3000 TR USD',
 'JHSC':'Russell 3000 TR USD',
 'KWEB':'MSCI China All Shares NR USD',
 'KVLE':'S&P 500 (TR)',
 'JHDV':'S&P 500 (TR)',
 'JHAC':'Russell 3000 TR USD',
 'YLDE':'Russell 3000 TR USD',
 'LRGE':'Russell 3000 TR USD',
 'LVHD':'Russell 3000 TR USD',
 'SQLV':'Russell 3000 TR USD',
 'BILD':'MSCI World NR USD',
 'PEXL':'S&P 900 TR',
 'KOOL':'S&P 500 (TR)',
 'ABEQ':'S&P 500 (TR)',
 'RAAX':'S&P 500 (TR)',
 'EPS':'S&P 500 (TR)',
 'DLN':'S&P 500 (TR)',
 'DON':'MSCI USA IMI NR USD',
 'EZM':'MSCI USA IMI NR USD',
 'DGRW':'S&P 500 (TR)',
 'DES':'MSCI USA IMI NR USD',
 'EES':'MSCI USA IMI NR USD',
 'DGRS':'MSCI USA IMI NR USD',
 'DTD':'MSCI USA IMI NR USD',
 'WTV':'MSCI USA IMI NR USD',
 'AIVL':'MSCI USA NR USD',
 'QMID':'MSCI USA NR USD',
 'QSML':'MSCI USA NR USD',
 'INDH':'MSCI India NR LCL',
 'MKAM':'S&P 500 (TR)',
 'NDOW':'Bloomberg US Agg Bond TR USD',
 'EMEQ':'MSCI EM NR USD',
 'LRGG':'Russell 1000 TR USD',
 'SEIS':'Russell 2000 TR USD',
 'FDAT':'S&P 500 (TR)',
 'WEEL':'S&P 500 (TR)',
 'MGK':'DJ US Total Stock Market TR USD',
 'MGC':'Morningstar US Mega TR USD',
 'VUG':'DJ US Total Stock Market TR USD',
 'VV':'Morningstar US Large TR USD',
 'VO':'DJ US Total Stock Market TR USD',
 'VOE':'DJ US Total Stock Market TR USD',
 'VBK':'DJ US Total Stock Market TR USD',
 'VB':'DJ US Total Stock Market TR USD',
 'VBR':'DJ US Total Stock Market TR USD',
 'VTI':'Morningstar US Total Market TR USD',
 'VOT':'DJ US Total Stock Market TR USD',
 'FFLS':'S&P 500 (TR) (1970)',
 'WTAI':'NASDAQ CTA Artificial Intlgc NR USD',
 'LGHT':'S&P 500 (TR) (1970)',
 'WCLD':'BVP Nasdaq Emerging Cloud USD',
 'VPL':'FTSE Global All Cap ex US TR USD',
 'VHT':'MSCI US Investable Market 2500 GR USD',
 'VIS':'MSCI US Investable Market 2500 NR USD',
 'VGT':'MSCI US Investable Market 2500 GR USD',
 'VAW':'MSCI US Investable Market 2500 NR USD',
 'VNQ':'DJ US Total Stock Market TR USD',
 'VONG':'DJ US Total Stock Market TR USD',
 'VONE':'Russell 1000 TR USD',
 'VONV':'DJ US Total Stock Market TR USD',
 'VTWG':'DJ US Total Stock Market TR USD',
 'VTWO':'Russell 2000 TR USD',
 'VTWV':'DJ US Total Stock Market TR USD',
 'VTHR':'Russell 3000 TR USD',
 'VCSH':'Bloomberg US Agg Float Adj TR USD',
 'VTC':'Bloomberg US Agg Float Adj TR USD',
 'VPU':'MSCI US Investable Market 2500 GR USD',
 'VSDA':'S&P 500 (TR) (1970)',
 'CFO':'S&P 500 (TR) (1970)',
 'CDC':'Russell 1000 TR USD',
 'CDL':'S&P 500 (TR) (1970)',
 'VSMV':'S&P 500 (TR) (1970)',
 'CSB':'Russell 3000 TR USD',
 'CXSE':'MSCI China NR USD',
 'DDLS':'MSCI EAFE NR LCL',
 'DGRE':'MSCI EM NR USD',
 'DGS':'MSCI EM NR USD',
 'HEDJ':'MSCI EMU Local Currency NR USD',
 'IHDG':'MSCI EAFE NR LCL',
 'DTH':'MSCI EAFE NR USD',
 'DOL':'MSCI EAFE NR USD',
 'IQDG':'MSCI EAFE NR USD',
 'DLS':'MSCI EAFE NR USD',
 'DXJ':'MSCI Japan NR LCL',
 'VCLN':'S&P Global BMI NR USD',
 'MODL':'S&P 500 (TR) (1970)',
 'TGLR':'S&P 500 (TR) (1970)',
 'VOX':'MSCI US Investable Market 2500 NR USD',
 'VFLO':'Victory US Large Cap Fre Cash Flo TR USD',
 'SFLO':'Russell 3000 TR USD',
 'GROZ':'Russell 3000 TR USD',
 'USMF':'S&P 500 Equal Weighted TR USD',
 'WCBR':'S&P 500 Equal Weighted TR USD',
 'NTSE':'MSCI EM NR USD',
 'ZECP':'Russell 3000 TR USD',
 'XC':'MSCI EM ex China NR USD',
 'GDMN':'S&P 500 (TR) (1970)',
 'SMIZ':'Russell 3000 TR USD',
 'DIVD':'Solactive GBS Glb Mar All Cap USD TR',
 'BAFE':'S&P 500 (TR)',
 'DIVP':'S&P 500 (TR)',
 'NEWZ':'Solactive GBS United States 1000 TR USD',
 'QDVO':'S&P 500 (TR)',
 'SROI':'MSCI ACWI GR USD',
 'CGGE':'MSCI World NR USD',
 'UPSD':'S&P 500 (TR)',
 'LQAI':'S&P 500 (TR)',
 'BWTG':'S&P 500 (TR)',
 'QFLR':'NASDAQ 100 TR USD',
 'OVLH':'S&P 500 (TR)',
 'FMCE':'S&P 500 Equal Weighted TR USD',
 'PSTR':'S&P 500 (TR)',
 'ONEY':'S&P 500 (TR) (1970)',
 'AESR':'S&P 500 (TR)',
 'EDOC':'Solactive Telemedicine&Dig Health NR USD',
 'CBLS':'Bloomberg World All Cap Eq Weight TR USD',
 'LSEQ':'S&P 500 (TR) (1970)',
 'CLIX':'S&P 500 (TR) (1970)',
 'LBAY':'S&P 500 (TR) (1970)',
 'SHRT':'S&P 500 (TR) (1970)',
 'CLSE':'Bloomberg US 3000 TR USD',
 'HDGE':'S&P 500 (TR) (1970)',
 'AMZA':'FT Wilshire 5000 TR USD',
 'XTAP':'S&P 500 (TR) (1970)',
 'XBAP':'S&P 500 (TR) (1970)',
 'GDE':'S&P 500 (TR) (1970)',
 'SCHD':'DJ US Dividend 100 TR USD',
};
